#include "output_2.h"

#define READ_RANGE(Arr, data_size, l)                                          \
  (Arr.data.range((data_size) * (l) + (data_size) - 1, (data_size) * (l)))

/****************************************************
 This file was automatically generated by Prometheus
****************************************************/
void load_vA1_for_task0(hls::stream<float16> &fifo_A1_from_off_chip_to_S0,
                        float16 vA1[10000]) {
#pragma HLS inline off
  for (int i = 0; i < 10000; i++) {
#pragma HLS pipeline II = 1
    fifo_A1_from_off_chip_to_S0.write(vA1[i]);
  }
}

void load_vB_for_task0(hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                       float16 vB[25]) {
#pragma HLS inline off
  for (int i = 0; i < 25; i++) {
#pragma HLS pipeline II = 1
    fifo_B_from_off_chip_to_S0.write(vB[i]);
  }
}

void load_vx1_for_task0(hls::stream<float4> &fifo_x1_from_off_chip_to_S0,
                        float4 vx1[100]) {
#pragma HLS inline off
  for (int i = 0; i < 100; i++) {
#pragma HLS pipeline II = 1
    fifo_x1_from_off_chip_to_S0.write(vx1[i]);
  }
}

void load_vC_for_task1(hls::stream<float16> &fifo_C_from_off_chip_to_S1,
                       float16 vC[25]) {
#pragma HLS inline off
  for (int i = 0; i < 25; i++) {
#pragma HLS pipeline II = 1
    fifo_C_from_off_chip_to_S1.write(vC[i]);
  }
}

void load_vx2_for_task1(hls::stream<float16> &fifo_x2_from_off_chip_to_S1,
                        float16 vx2[25]) {
#pragma HLS inline off
  for (int i = 0; i < 25; i++) {
#pragma HLS pipeline II = 1
    fifo_x2_from_off_chip_to_S1.write(vx2[i]);
  }
}

void load_vA2_for_task1(hls::stream<float16> &fifo_A2_from_off_chip_to_S1,
                        float16 vA2[10000]) {
#pragma HLS inline off
  for (int i = 0; i < 10000; i++) {
#pragma HLS pipeline II = 1
    fifo_A2_from_off_chip_to_S1.write(vA2[i]);
  }
}

void store_vx2_for_task1(hls::stream<float16> &fifo_x2_to_off_chip,
                         float16 vx2[25]) {
#pragma HLS inline off
  for (int i = 0; i < 25; i++) {
#pragma HLS pipeline II = 1
    vx2[i] = fifo_x2_to_off_chip.read();
  }
}

void store_vx1_for_task0(hls::stream<float4> &fifo_x1_to_off_chip,
                         float4 vx1[100]) {
#pragma HLS inline off
  for (int i = 0; i < 100; i++) {
#pragma HLS pipeline II = 1
    vx1[i] = fifo_x1_to_off_chip.read();
  }
}

void compute_FT0_level0(hls::stream<float16> &fifo_A1_from_off_chip_to_S0,
                        hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                        hls::stream<float4> &fifo_x1_from_off_chip_to_S0,
                        hls::stream<float4> &fifo_x1_to_off_chip, int i0,
                        float x1_0[4], float x1_1[4], float x1_2[4],
                        float A1_0[4][400], float A1_1[4][400],
                        float A1_2[4][400], float B[400]) {
#pragma HLS inline off
#pragma HLS dataflow
  read_x1_FT0(x1_0, fifo_x1_from_off_chip_to_S0, i0 + 1);
  read_A1_FT0(A1_0, fifo_A1_from_off_chip_to_S0, i0 + 1);
  task0_intra(x1_1, A1_1, B, i0);
  write_x1_FT0(x1_2, fifo_x1_to_off_chip, i0 - 1);
}

void FT0_level0(hls::stream<float16> &fifo_A1_from_off_chip_to_S0,
                hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                hls::stream<float4> &fifo_x1_from_off_chip_to_S0,
                hls::stream<float4> &fifo_x1_to_off_chip) {
#pragma HLS inline off
  float x1_0[4];
  // FT0
#pragma HLS array_partition variable = x1_0 cyclic factor = 4 dim = 1
  float x1_1[4];
  // FT0
#pragma HLS array_partition variable = x1_1 cyclic factor = 4 dim = 1
  float x1_2[4];
  // FT0
#pragma HLS array_partition variable = x1_2 cyclic factor = 4 dim = 1
  float A1_0[4][400];
  // FT0
#pragma HLS array_partition variable = A1_0 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = A1_0 cyclic factor = 100 dim = 2
  float A1_1[4][400];
  // FT0
#pragma HLS array_partition variable = A1_1 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = A1_1 cyclic factor = 100 dim = 2
  float A1_2[4][400];
  // FT0
#pragma HLS array_partition variable = A1_2 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = A1_2 cyclic factor = 100 dim = 2
  float B[400];
#pragma HLS array_partition variable = B cyclic factor = 100 dim = 1
  read_B_FT0(B, fifo_B_from_off_chip_to_S0);
  read_x1_FT0(x1_0, fifo_x1_from_off_chip_to_S0, 0);
  read_A1_FT0(A1_0, fifo_A1_from_off_chip_to_S0, 0);
  for (int i0 = 0; i0 < 100; i0++) {
    if (i0 % 3 == 0) {
      //     read_x1_FT0(x1_1, fifo_x1_from_off_chip_to_S0, i0+1);
      //     read_A1_FT0(A1_1, fifo_A1_from_off_chip_to_S0, i0+1);
      //     task0_intra(x1_0, A1_0, B, i0);
      //     write_x1_FT0(x1_2, fifo_x1_to_off_chip, i0-1);
      compute_FT0_level0(fifo_A1_from_off_chip_to_S0,
                         fifo_B_from_off_chip_to_S0,
                         fifo_x1_from_off_chip_to_S0, fifo_x1_to_off_chip, i0,
                         x1_1, x1_0, x1_2, A1_1, A1_0, A1_2, B);
    } else if (i0 % 3 == 1) {
      //     read_x1_FT0(x1_2, fifo_x1_from_off_chip_to_S0, i0+1);
      //     read_A1_FT0(A1_2, fifo_A1_from_off_chip_to_S0, i0+1);
      //     task0_intra(x1_1, A1_1, B, i0);
      //     write_x1_FT0(x1_0, fifo_x1_to_off_chip, i0-1);
      compute_FT0_level0(fifo_A1_from_off_chip_to_S0,
                         fifo_B_from_off_chip_to_S0,
                         fifo_x1_from_off_chip_to_S0, fifo_x1_to_off_chip, i0,
                         x1_2, x1_1, x1_0, A1_2, A1_1, A1_0, B);
    } else if (i0 % 3 == 2) {
      //     read_x1_FT0(x1_0, fifo_x1_from_off_chip_to_S0, i0+1);
      //     read_A1_FT0(A1_0, fifo_A1_from_off_chip_to_S0, i0+1);
      //     task0_intra(x1_2, A1_2, B, i0);
      //     write_x1_FT0(x1_1, fifo_x1_to_off_chip, i0-1);
      compute_FT0_level0(fifo_A1_from_off_chip_to_S0,
                         fifo_B_from_off_chip_to_S0,
                         fifo_x1_from_off_chip_to_S0, fifo_x1_to_off_chip, i0,
                         x1_0, x1_2, x1_1, A1_0, A1_2, A1_1, B);
    }
  }
  write_x1_FT0(x1_0, fifo_x1_to_off_chip, 99);
}
void compute_FT1_level0(hls::stream<float16> &fifo_C_from_off_chip_to_S1,
                        hls::stream<float16> &fifo_x2_from_off_chip_to_S1,
                        hls::stream<float16> &fifo_A2_from_off_chip_to_S1,
                        hls::stream<float16> &fifo_x2_to_off_chip, int i0,
                        float x2_0[16], float x2_1[16], float x2_2[16],
                        float A2_0[400][16], float A2_1[400][16],
                        float A2_2[400][16], float C[400]) {
#pragma HLS inline off
#pragma HLS dataflow
  read_x2_FT1(x2_0, fifo_x2_from_off_chip_to_S1, i0 + 1);
  read_A2_FT1(A2_0, fifo_A2_from_off_chip_to_S1, i0 + 1);
  task1_intra(x2_1, A2_1, C, i0);
  write_x2_FT1(x2_2, fifo_x2_to_off_chip, i0 - 1);
}

void FT1_level0(hls::stream<float16> &fifo_C_from_off_chip_to_S1,
                hls::stream<float16> &fifo_x2_from_off_chip_to_S1,
                hls::stream<float16> &fifo_A2_from_off_chip_to_S1,
                hls::stream<float16> &fifo_x2_to_off_chip) {
#pragma HLS inline off
  float x2_0[16];
  // FT1
#pragma HLS array_partition variable = x2_0 cyclic factor = 16 dim = 1
  float x2_1[16];
  // FT1
#pragma HLS array_partition variable = x2_1 cyclic factor = 16 dim = 1
  float x2_2[16];
  // FT1
#pragma HLS array_partition variable = x2_2 cyclic factor = 16 dim = 1
  float A2_0[400][16];
  // FT1
#pragma HLS array_partition variable = A2_0 cyclic factor = 50 dim = 1
#pragma HLS array_partition variable = A2_0 cyclic factor = 16 dim = 2
  float A2_1[400][16];
  // FT1
#pragma HLS array_partition variable = A2_1 cyclic factor = 50 dim = 1
#pragma HLS array_partition variable = A2_1 cyclic factor = 16 dim = 2
  float A2_2[400][16];
  // FT1
#pragma HLS array_partition variable = A2_2 cyclic factor = 50 dim = 1
#pragma HLS array_partition variable = A2_2 cyclic factor = 16 dim = 2
  float C[400];
#pragma HLS array_partition variable = C cyclic factor = 50 dim = 1
  read_C_FT1(C, fifo_C_from_off_chip_to_S1);
  read_x2_FT1(x2_0, fifo_x2_from_off_chip_to_S1, 0);
  read_A2_FT1(A2_0, fifo_A2_from_off_chip_to_S1, 0);
  for (int i0 = 0; i0 < 25; i0++) {
    if (i0 % 3 == 0) {
      //     read_x2_FT1(x2_1, fifo_x2_from_off_chip_to_S1, i0+1);
      //     read_A2_FT1(A2_1, fifo_A2_from_off_chip_to_S1, i0+1);
      //     task1_intra(x2_0, A2_0, C, i0);
      //     write_x2_FT1(x2_2, fifo_x2_to_off_chip, i0-1);
      compute_FT1_level0(fifo_C_from_off_chip_to_S1,
                         fifo_x2_from_off_chip_to_S1,
                         fifo_A2_from_off_chip_to_S1, fifo_x2_to_off_chip, i0,
                         x2_1, x2_0, x2_2, A2_1, A2_0, A2_2, C);
    } else if (i0 % 3 == 1) {
      //     read_x2_FT1(x2_2, fifo_x2_from_off_chip_to_S1, i0+1);
      //     read_A2_FT1(A2_2, fifo_A2_from_off_chip_to_S1, i0+1);
      //     task1_intra(x2_1, A2_1, C, i0);
      //     write_x2_FT1(x2_0, fifo_x2_to_off_chip, i0-1);
      compute_FT1_level0(fifo_C_from_off_chip_to_S1,
                         fifo_x2_from_off_chip_to_S1,
                         fifo_A2_from_off_chip_to_S1, fifo_x2_to_off_chip, i0,
                         x2_2, x2_1, x2_0, A2_2, A2_1, A2_0, C);
    } else if (i0 % 3 == 2) {
      //     read_x2_FT1(x2_0, fifo_x2_from_off_chip_to_S1, i0+1);
      //     read_A2_FT1(A2_0, fifo_A2_from_off_chip_to_S1, i0+1);
      //     task1_intra(x2_2, A2_2, C, i0);
      //     write_x2_FT1(x2_1, fifo_x2_to_off_chip, i0-1);
      compute_FT1_level0(fifo_C_from_off_chip_to_S1,
                         fifo_x2_from_off_chip_to_S1,
                         fifo_A2_from_off_chip_to_S1, fifo_x2_to_off_chip, i0,
                         x2_0, x2_2, x2_1, A2_0, A2_2, A2_1, C);
    }
  }
  write_x2_FT1(x2_0, fifo_x2_to_off_chip, 24);
}
void task0_intra(float x1[4], float A1[4][400], float B[400], int i0) {
#pragma HLS inline off
  int i;
  int j;
  for (int j0 = 0; j0 < 4; j0++) {
#pragma HLS pipeline II = 2
    for (int i1 = 0; i1 < 4; i1++) {
#pragma HLS unroll
      for (int j1 = 0; j1 < 100; j1++) {
#pragma HLS unroll
        i = i0 * 4 + i1;
        j = j0 * 100 + j1;
        x1[i1] = x1[i1] + A1[i1][j] * B[j];
      }
    }
  }
}

void task1_intra(float x2[16], float A2[400][16], float C[400], int i0) {
#pragma HLS inline off
  int i;
  int j;
  for (int j0 = 0; j0 < 8; j0++) {
#pragma HLS pipeline II = 2
    for (int i1 = 0; i1 < 16; i1++) {
#pragma HLS unroll
      for (int j1 = 0; j1 < 50; j1++) {
#pragma HLS unroll
        i = i0 * 16 + i1;
        j = j0 * 50 + j1;
        x2[i1] = x2[i1] + A2[j][i1] * C[j];
      }
    }
  }
}

void read_B_FT0(float B[400],
                hls::stream<float16> &fifo_B_from_off_chip_to_S0) {
#pragma HLS inline off
  for (int d0 = 0; d0 < 400; d0 += 16) {
#pragma HLS pipeline II = 1
    float16 tmp_fifo = fifo_B_from_off_chip_to_S0.read();
    B[d0 + 0 + 0] = tmp_fifo[0];
    B[d0 + 0 + 1] = tmp_fifo[1];
    B[d0 + 0 + 2] = tmp_fifo[2];
    B[d0 + 0 + 3] = tmp_fifo[3];
    B[d0 + 0 + 4] = tmp_fifo[4];
    B[d0 + 0 + 5] = tmp_fifo[5];
    B[d0 + 0 + 6] = tmp_fifo[6];
    B[d0 + 0 + 7] = tmp_fifo[7];
    B[d0 + 0 + 8] = tmp_fifo[8];
    B[d0 + 0 + 9] = tmp_fifo[9];
    B[d0 + 0 + 10] = tmp_fifo[10];
    B[d0 + 0 + 11] = tmp_fifo[11];
    B[d0 + 0 + 12] = tmp_fifo[12];
    B[d0 + 0 + 13] = tmp_fifo[13];
    B[d0 + 0 + 14] = tmp_fifo[14];
    B[d0 + 0 + 15] = tmp_fifo[15];
  }
}

void read_x1_FT0(float x1[4], hls::stream<float4> &fifo_x1_from_off_chip_to_S0,
                 int i0) {
#pragma HLS inline off
  if (i0 >= 100) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0 += 4) {
#pragma HLS pipeline II = 1
    float4 tmp_fifo = fifo_x1_from_off_chip_to_S0.read();
    x1[d0 + 0 + 0] = tmp_fifo[0];
    x1[d0 + 0 + 1] = tmp_fifo[1];
    x1[d0 + 0 + 2] = tmp_fifo[2];
    x1[d0 + 0 + 3] = tmp_fifo[3];
  }
}

void read_A1_FT0(float A1[4][400],
                 hls::stream<float16> &fifo_A1_from_off_chip_to_S0, int i0) {
#pragma HLS inline off
  if (i0 >= 100) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 400; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_A1_from_off_chip_to_S0.read();
      A1[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      A1[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      A1[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      A1[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      A1[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      A1[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      A1[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      A1[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      A1[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      A1[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      A1[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      A1[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      A1[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      A1[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      A1[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      A1[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}

void read_C_FT1(float C[400],
                hls::stream<float16> &fifo_C_from_off_chip_to_S1) {
#pragma HLS inline off
  for (int d0 = 0; d0 < 400; d0 += 16) {
#pragma HLS pipeline II = 1
    float16 tmp_fifo = fifo_C_from_off_chip_to_S1.read();
    C[d0 + 0 + 0] = tmp_fifo[0];
    C[d0 + 0 + 1] = tmp_fifo[1];
    C[d0 + 0 + 2] = tmp_fifo[2];
    C[d0 + 0 + 3] = tmp_fifo[3];
    C[d0 + 0 + 4] = tmp_fifo[4];
    C[d0 + 0 + 5] = tmp_fifo[5];
    C[d0 + 0 + 6] = tmp_fifo[6];
    C[d0 + 0 + 7] = tmp_fifo[7];
    C[d0 + 0 + 8] = tmp_fifo[8];
    C[d0 + 0 + 9] = tmp_fifo[9];
    C[d0 + 0 + 10] = tmp_fifo[10];
    C[d0 + 0 + 11] = tmp_fifo[11];
    C[d0 + 0 + 12] = tmp_fifo[12];
    C[d0 + 0 + 13] = tmp_fifo[13];
    C[d0 + 0 + 14] = tmp_fifo[14];
    C[d0 + 0 + 15] = tmp_fifo[15];
  }
}

void read_x2_FT1(float x2[16],
                 hls::stream<float16> &fifo_x2_from_off_chip_to_S1, int i0) {
#pragma HLS inline off
  if (i0 >= 25) {
    return;
  }
  for (int d0 = 0; d0 < 16; d0 += 16) {
#pragma HLS pipeline II = 1
    float16 tmp_fifo = fifo_x2_from_off_chip_to_S1.read();
    x2[d0 + 0 + 0] = tmp_fifo[0];
    x2[d0 + 0 + 1] = tmp_fifo[1];
    x2[d0 + 0 + 2] = tmp_fifo[2];
    x2[d0 + 0 + 3] = tmp_fifo[3];
    x2[d0 + 0 + 4] = tmp_fifo[4];
    x2[d0 + 0 + 5] = tmp_fifo[5];
    x2[d0 + 0 + 6] = tmp_fifo[6];
    x2[d0 + 0 + 7] = tmp_fifo[7];
    x2[d0 + 0 + 8] = tmp_fifo[8];
    x2[d0 + 0 + 9] = tmp_fifo[9];
    x2[d0 + 0 + 10] = tmp_fifo[10];
    x2[d0 + 0 + 11] = tmp_fifo[11];
    x2[d0 + 0 + 12] = tmp_fifo[12];
    x2[d0 + 0 + 13] = tmp_fifo[13];
    x2[d0 + 0 + 14] = tmp_fifo[14];
    x2[d0 + 0 + 15] = tmp_fifo[15];
  }
}

void read_A2_FT1(float A2[400][16],
                 hls::stream<float16> &fifo_A2_from_off_chip_to_S1, int i0) {
#pragma HLS inline off
  if (i0 >= 25) {
    return;
  }
  for (int d0 = 0; d0 < 400; d0++) {
    for (int d1 = 0; d1 < 16; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_A2_from_off_chip_to_S1.read();
      A2[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      A2[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      A2[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      A2[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      A2[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      A2[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      A2[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      A2[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      A2[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      A2[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      A2[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      A2[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      A2[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      A2[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      A2[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      A2[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}

void write_x1_FT0(float x1[4], hls::stream<float4> &fifo_x1_to_off_chip,
                  int i0) {
#pragma HLS inline off
  if (i0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0 += 4) {
#pragma HLS pipeline II = 1
    float4 tmp_fifo;
    tmp_fifo[0] = x1[d0 + 0 + 0];
    tmp_fifo[1] = x1[d0 + 0 + 1];
    tmp_fifo[2] = x1[d0 + 0 + 2];
    tmp_fifo[3] = x1[d0 + 0 + 3];
    fifo_x1_to_off_chip.write(tmp_fifo);
  }
}

void write_x2_FT1(float x2[16], hls::stream<float16> &fifo_x2_to_off_chip,
                  int i0) {
#pragma HLS inline off
  if (i0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 16; d0 += 16) {
#pragma HLS pipeline II = 1
    float16 tmp_fifo;
    tmp_fifo[0] = x2[d0 + 0 + 0];
    tmp_fifo[1] = x2[d0 + 0 + 1];
    tmp_fifo[2] = x2[d0 + 0 + 2];
    tmp_fifo[3] = x2[d0 + 0 + 3];
    tmp_fifo[4] = x2[d0 + 0 + 4];
    tmp_fifo[5] = x2[d0 + 0 + 5];
    tmp_fifo[6] = x2[d0 + 0 + 6];
    tmp_fifo[7] = x2[d0 + 0 + 7];
    tmp_fifo[8] = x2[d0 + 0 + 8];
    tmp_fifo[9] = x2[d0 + 0 + 9];
    tmp_fifo[10] = x2[d0 + 0 + 10];
    tmp_fifo[11] = x2[d0 + 0 + 11];
    tmp_fifo[12] = x2[d0 + 0 + 12];
    tmp_fifo[13] = x2[d0 + 0 + 13];
    tmp_fifo[14] = x2[d0 + 0 + 14];
    tmp_fifo[15] = x2[d0 + 0 + 15];
    fifo_x2_to_off_chip.write(tmp_fifo);
  }
}

// extern "C"{
void kernel_nlp(float4 vx1_for_task0[100], float16 vA1_for_task0[10000],
                float16 vB_for_task0[25], float16 vx2_for_task1[25],
                float16 vA2_for_task1[10000], float16 vC_for_task1[25]) {

#pragma HLS INTERFACE m_axi port = vx1_for_task0 offset = slave bundle =       \
    kernel_vx1_for_task0
#pragma HLS INTERFACE m_axi port = vA1_for_task0 offset = slave bundle =       \
    kernel_vA1_for_task0
#pragma HLS INTERFACE m_axi port = vB_for_task0 offset = slave bundle =        \
    kernel_vB_for_task0
#pragma HLS INTERFACE m_axi port = vx2_for_task1 offset = slave bundle =       \
    kernel_vx2_for_task1
#pragma HLS INTERFACE m_axi port = vA2_for_task1 offset = slave bundle =       \
    kernel_vA2_for_task1
#pragma HLS INTERFACE m_axi port = vC_for_task1 offset = slave bundle =        \
    kernel_vC_for_task1
#pragma HLS INTERFACE s_axilite port = vx1_for_task0 bundle = control
#pragma HLS INTERFACE s_axilite port = vA1_for_task0 bundle = control
#pragma HLS INTERFACE s_axilite port = vB_for_task0 bundle = control
#pragma HLS INTERFACE s_axilite port = vx2_for_task1 bundle = control
#pragma HLS INTERFACE s_axilite port = vA2_for_task1 bundle = control
#pragma HLS INTERFACE s_axilite port = vC_for_task1 bundle = control
#pragma HLS DATA_PACK VARIABLE = vx1_for_task0
#pragma HLS DATA_PACK VARIABLE = vA1_for_task0
#pragma HLS DATA_PACK VARIABLE = vB_for_task0
#pragma HLS DATA_PACK VARIABLE = vx2_for_task1
#pragma HLS DATA_PACK VARIABLE = vA2_for_task1
#pragma HLS DATA_PACK VARIABLE = vC_for_task1
#pragma HLS INTERFACE s_axilite port = return bundle = control

#pragma HLS dataflow

  hls::stream<float16> fifo_A1_from_off_chip_to_S0;
#pragma HLS stream variable = fifo_A1_from_off_chip_to_S0 depth = 512
  hls::stream<float16> fifo_B_from_off_chip_to_S0;
#pragma HLS stream variable = fifo_B_from_off_chip_to_S0 depth = 512
  hls::stream<float4> fifo_x1_from_off_chip_to_S0;
#pragma HLS stream variable = fifo_x1_from_off_chip_to_S0 depth = 512
  hls::stream<float16> fifo_C_from_off_chip_to_S1;
#pragma HLS stream variable = fifo_C_from_off_chip_to_S1 depth = 512
  hls::stream<float16> fifo_x2_from_off_chip_to_S1;
#pragma HLS stream variable = fifo_x2_from_off_chip_to_S1 depth = 512
  hls::stream<float16> fifo_A2_from_off_chip_to_S1;
#pragma HLS stream variable = fifo_A2_from_off_chip_to_S1 depth = 512
  hls::stream<float16> fifo_x2_to_off_chip;
#pragma HLS stream variable = fifo_x2_to_off_chip depth = 512
  hls::stream<float4> fifo_x1_to_off_chip;
#pragma HLS stream variable = fifo_x1_to_off_chip depth = 512

  load_vA1_for_task0(fifo_A1_from_off_chip_to_S0, vA1_for_task0);
  load_vB_for_task0(fifo_B_from_off_chip_to_S0, vB_for_task0);
  load_vx1_for_task0(fifo_x1_from_off_chip_to_S0, vx1_for_task0);
  load_vC_for_task1(fifo_C_from_off_chip_to_S1, vC_for_task1);
  load_vx2_for_task1(fifo_x2_from_off_chip_to_S1, vx2_for_task1);
  load_vA2_for_task1(fifo_A2_from_off_chip_to_S1, vA2_for_task1);

  FT0_level0(fifo_A1_from_off_chip_to_S0, fifo_B_from_off_chip_to_S0,
             fifo_x1_from_off_chip_to_S0, fifo_x1_to_off_chip);
  FT1_level0(fifo_C_from_off_chip_to_S1, fifo_x2_from_off_chip_to_S1,
             fifo_A2_from_off_chip_to_S1, fifo_x2_to_off_chip);

  store_vx2_for_task1(fifo_x2_to_off_chip, vx2_for_task1);
  store_vx1_for_task0(fifo_x1_to_off_chip, vx1_for_task0);
}
//}
