#include "output.h"

#define READ_RANGE(Arr, data_size, l)                                          \
  (Arr.data.range((data_size) * (l) + (data_size) - 1, (data_size) * (l)))

/****************************************************
 This file was automatically generated by Prometheus
****************************************************/
void load_vC_for_task3(hls::stream<float16> &fifo_C_from_off_chip_to_S3,
                       float16 vC[2688]) {
#pragma HLS inline off
  for (int i = 0; i < 2688; i++) {
#pragma HLS pipeline II = 1
    fifo_C_from_off_chip_to_S3.write(vC[i]);
  }
}
void load_vC_for_task3(
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_C_from_off_chip_to_S3,
    float16 vC[2688]) {
#pragma HLS inline off
  for (int i = 0; i < 2688; i++) {
#pragma HLS pipeline II = 1
    float16 vC_off = vC[i];
    ap_axiu<512, 0, 0, 0> vC_on;
    vC_on.data.range(31, 0) = *(uint32_t *)(&vC_off[0]);
    vC_on.data.range(63, 32) = *(uint32_t *)(&vC_off[1]);
    vC_on.data.range(95, 64) = *(uint32_t *)(&vC_off[2]);
    vC_on.data.range(127, 96) = *(uint32_t *)(&vC_off[3]);
    vC_on.data.range(159, 128) = *(uint32_t *)(&vC_off[4]);
    vC_on.data.range(191, 160) = *(uint32_t *)(&vC_off[5]);
    vC_on.data.range(223, 192) = *(uint32_t *)(&vC_off[6]);
    vC_on.data.range(255, 224) = *(uint32_t *)(&vC_off[7]);
    vC_on.data.range(287, 256) = *(uint32_t *)(&vC_off[8]);
    vC_on.data.range(319, 288) = *(uint32_t *)(&vC_off[9]);
    vC_on.data.range(351, 320) = *(uint32_t *)(&vC_off[10]);
    vC_on.data.range(383, 352) = *(uint32_t *)(&vC_off[11]);
    vC_on.data.range(415, 384) = *(uint32_t *)(&vC_off[12]);
    vC_on.data.range(447, 416) = *(uint32_t *)(&vC_off[13]);
    vC_on.data.range(479, 448) = *(uint32_t *)(&vC_off[14]);
    vC_on.data.range(511, 480) = *(uint32_t *)(&vC_off[15]);
    fifo_C_from_off_chip_to_S3.write(vC_on);
  }
}
void load_vD_for_task2(hls::stream<float16> &fifo_D_from_off_chip_to_S2,
                       float16 vD[2520]) {
#pragma HLS inline off
  for (int i = 0; i < 2520; i++) {
#pragma HLS pipeline II = 1
    fifo_D_from_off_chip_to_S2.write(vD[i]);
  }
}
void load_vD_for_task2(
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_D_from_off_chip_to_S2,
    float16 vD[2520]) {
#pragma HLS inline off
  for (int i = 0; i < 2520; i++) {
#pragma HLS pipeline II = 1
    float16 vD_off = vD[i];
    ap_axiu<512, 0, 0, 0> vD_on;
    vD_on.data.range(31, 0) = *(uint32_t *)(&vD_off[0]);
    vD_on.data.range(63, 32) = *(uint32_t *)(&vD_off[1]);
    vD_on.data.range(95, 64) = *(uint32_t *)(&vD_off[2]);
    vD_on.data.range(127, 96) = *(uint32_t *)(&vD_off[3]);
    vD_on.data.range(159, 128) = *(uint32_t *)(&vD_off[4]);
    vD_on.data.range(191, 160) = *(uint32_t *)(&vD_off[5]);
    vD_on.data.range(223, 192) = *(uint32_t *)(&vD_off[6]);
    vD_on.data.range(255, 224) = *(uint32_t *)(&vD_off[7]);
    vD_on.data.range(287, 256) = *(uint32_t *)(&vD_off[8]);
    vD_on.data.range(319, 288) = *(uint32_t *)(&vD_off[9]);
    vD_on.data.range(351, 320) = *(uint32_t *)(&vD_off[10]);
    vD_on.data.range(383, 352) = *(uint32_t *)(&vD_off[11]);
    vD_on.data.range(415, 384) = *(uint32_t *)(&vD_off[12]);
    vD_on.data.range(447, 416) = *(uint32_t *)(&vD_off[13]);
    vD_on.data.range(479, 448) = *(uint32_t *)(&vD_off[14]);
    vD_on.data.range(511, 480) = *(uint32_t *)(&vD_off[15]);
    fifo_D_from_off_chip_to_S2.write(vD_on);
  }
}
void load_vA_for_task1(hls::stream<float16> &fifo_A_from_off_chip_to_S1,
                       float16 vA[2520]) {
#pragma HLS inline off
  for (int i = 0; i < 2520; i++) {
#pragma HLS pipeline II = 1
    fifo_A_from_off_chip_to_S1.write(vA[i]);
  }
}
void load_vA_for_task1(
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_A_from_off_chip_to_S1,
    float16 vA[2520]) {
#pragma HLS inline off
  for (int i = 0; i < 2520; i++) {
#pragma HLS pipeline II = 1
    float16 vA_off = vA[i];
    ap_axiu<512, 0, 0, 0> vA_on;
    vA_on.data.range(31, 0) = *(uint32_t *)(&vA_off[0]);
    vA_on.data.range(63, 32) = *(uint32_t *)(&vA_off[1]);
    vA_on.data.range(95, 64) = *(uint32_t *)(&vA_off[2]);
    vA_on.data.range(127, 96) = *(uint32_t *)(&vA_off[3]);
    vA_on.data.range(159, 128) = *(uint32_t *)(&vA_off[4]);
    vA_on.data.range(191, 160) = *(uint32_t *)(&vA_off[5]);
    vA_on.data.range(223, 192) = *(uint32_t *)(&vA_off[6]);
    vA_on.data.range(255, 224) = *(uint32_t *)(&vA_off[7]);
    vA_on.data.range(287, 256) = *(uint32_t *)(&vA_off[8]);
    vA_on.data.range(319, 288) = *(uint32_t *)(&vA_off[9]);
    vA_on.data.range(351, 320) = *(uint32_t *)(&vA_off[10]);
    vA_on.data.range(383, 352) = *(uint32_t *)(&vA_off[11]);
    vA_on.data.range(415, 384) = *(uint32_t *)(&vA_off[12]);
    vA_on.data.range(447, 416) = *(uint32_t *)(&vA_off[13]);
    vA_on.data.range(479, 448) = *(uint32_t *)(&vA_off[14]);
    vA_on.data.range(511, 480) = *(uint32_t *)(&vA_off[15]);
    fifo_A_from_off_chip_to_S1.write(vA_on);
  }
}
void load_vB_for_task1(hls::stream<float16> &fifo_B_from_off_chip_to_S1,
                       float16 vB[2544]) {
#pragma HLS inline off
  for (int i = 0; i < 2544; i++) {
#pragma HLS pipeline II = 1
    fifo_B_from_off_chip_to_S1.write(vB[i]);
  }
}
void load_vB_for_task1(
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_B_from_off_chip_to_S1,
    float16 vB[2544]) {
#pragma HLS inline off
  for (int i = 0; i < 2544; i++) {
#pragma HLS pipeline II = 1
    float16 vB_off = vB[i];
    ap_axiu<512, 0, 0, 0> vB_on;
    vB_on.data.range(31, 0) = *(uint32_t *)(&vB_off[0]);
    vB_on.data.range(63, 32) = *(uint32_t *)(&vB_off[1]);
    vB_on.data.range(95, 64) = *(uint32_t *)(&vB_off[2]);
    vB_on.data.range(127, 96) = *(uint32_t *)(&vB_off[3]);
    vB_on.data.range(159, 128) = *(uint32_t *)(&vB_off[4]);
    vB_on.data.range(191, 160) = *(uint32_t *)(&vB_off[5]);
    vB_on.data.range(223, 192) = *(uint32_t *)(&vB_off[6]);
    vB_on.data.range(255, 224) = *(uint32_t *)(&vB_off[7]);
    vB_on.data.range(287, 256) = *(uint32_t *)(&vB_off[8]);
    vB_on.data.range(319, 288) = *(uint32_t *)(&vB_off[9]);
    vB_on.data.range(351, 320) = *(uint32_t *)(&vB_off[10]);
    vB_on.data.range(383, 352) = *(uint32_t *)(&vB_off[11]);
    vB_on.data.range(415, 384) = *(uint32_t *)(&vB_off[12]);
    vB_on.data.range(447, 416) = *(uint32_t *)(&vB_off[13]);
    vB_on.data.range(479, 448) = *(uint32_t *)(&vB_off[14]);
    vB_on.data.range(511, 480) = *(uint32_t *)(&vB_off[15]);
    fifo_B_from_off_chip_to_S1.write(vB_on);
  }
}
void store_vtmp_for_task1(hls::stream<float16> &fifo_tmp_to_off_chip,
                          float16 vtmp[2160]) {
#pragma HLS inline off
  for (int i = 0; i < 2160; i++) {
#pragma HLS pipeline II = 1
    vtmp[i] = fifo_tmp_to_off_chip.read();
  }
}
void store_vtmp_for_task1(
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_tmp_to_off_chip,
    float16 vtmp[2160]) {
#pragma HLS inline off
  for (int i = 0; i < 2160; i++) {
#pragma HLS pipeline II = 1
    float16 vtmp_off;
    ap_axiu<512, 0, 0, 0> vtmp_on = fifo_tmp_to_off_chip.read();
    uint32_t vtmp_tmp[16];
    vtmp_tmp[0] = vtmp_on.data.range(31, 0);
    vtmp_off[0] = *(float *)(&vtmp_tmp[0]);
    vtmp_tmp[1] = vtmp_on.data.range(63, 32);
    vtmp_off[1] = *(float *)(&vtmp_tmp[1]);
    vtmp_tmp[2] = vtmp_on.data.range(95, 64);
    vtmp_off[2] = *(float *)(&vtmp_tmp[2]);
    vtmp_tmp[3] = vtmp_on.data.range(127, 96);
    vtmp_off[3] = *(float *)(&vtmp_tmp[3]);
    vtmp_tmp[4] = vtmp_on.data.range(159, 128);
    vtmp_off[4] = *(float *)(&vtmp_tmp[4]);
    vtmp_tmp[5] = vtmp_on.data.range(191, 160);
    vtmp_off[5] = *(float *)(&vtmp_tmp[5]);
    vtmp_tmp[6] = vtmp_on.data.range(223, 192);
    vtmp_off[6] = *(float *)(&vtmp_tmp[6]);
    vtmp_tmp[7] = vtmp_on.data.range(255, 224);
    vtmp_off[7] = *(float *)(&vtmp_tmp[7]);
    vtmp_tmp[8] = vtmp_on.data.range(287, 256);
    vtmp_off[8] = *(float *)(&vtmp_tmp[8]);
    vtmp_tmp[9] = vtmp_on.data.range(319, 288);
    vtmp_off[9] = *(float *)(&vtmp_tmp[9]);
    vtmp_tmp[10] = vtmp_on.data.range(351, 320);
    vtmp_off[10] = *(float *)(&vtmp_tmp[10]);
    vtmp_tmp[11] = vtmp_on.data.range(383, 352);
    vtmp_off[11] = *(float *)(&vtmp_tmp[11]);
    vtmp_tmp[12] = vtmp_on.data.range(415, 384);
    vtmp_off[12] = *(float *)(&vtmp_tmp[12]);
    vtmp_tmp[13] = vtmp_on.data.range(447, 416);
    vtmp_off[13] = *(float *)(&vtmp_tmp[13]);
    vtmp_tmp[14] = vtmp_on.data.range(479, 448);
    vtmp_off[14] = *(float *)(&vtmp_tmp[14]);
    vtmp_tmp[15] = vtmp_on.data.range(511, 480);
    vtmp_off[15] = *(float *)(&vtmp_tmp[15]);
    vtmp[i] = vtmp_off;
  }
}
void store_vD_for_task2(hls::stream<float16> &fifo_D_to_off_chip,
                        float16 vD[2520]) {
#pragma HLS inline off
  for (int i = 0; i < 2520; i++) {
#pragma HLS pipeline II = 1
    vD[i] = fifo_D_to_off_chip.read();
  }
}
void store_vD_for_task2(hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_D_to_off_chip,
                        float16 vD[2520]) {
#pragma HLS inline off
  for (int i = 0; i < 2520; i++) {
#pragma HLS pipeline II = 1
    float16 vD_off;
    ap_axiu<512, 0, 0, 0> vD_on = fifo_D_to_off_chip.read();
    uint32_t vD_tmp[16];
    vD_tmp[0] = vD_on.data.range(31, 0);
    vD_off[0] = *(float *)(&vD_tmp[0]);
    vD_tmp[1] = vD_on.data.range(63, 32);
    vD_off[1] = *(float *)(&vD_tmp[1]);
    vD_tmp[2] = vD_on.data.range(95, 64);
    vD_off[2] = *(float *)(&vD_tmp[2]);
    vD_tmp[3] = vD_on.data.range(127, 96);
    vD_off[3] = *(float *)(&vD_tmp[3]);
    vD_tmp[4] = vD_on.data.range(159, 128);
    vD_off[4] = *(float *)(&vD_tmp[4]);
    vD_tmp[5] = vD_on.data.range(191, 160);
    vD_off[5] = *(float *)(&vD_tmp[5]);
    vD_tmp[6] = vD_on.data.range(223, 192);
    vD_off[6] = *(float *)(&vD_tmp[6]);
    vD_tmp[7] = vD_on.data.range(255, 224);
    vD_off[7] = *(float *)(&vD_tmp[7]);
    vD_tmp[8] = vD_on.data.range(287, 256);
    vD_off[8] = *(float *)(&vD_tmp[8]);
    vD_tmp[9] = vD_on.data.range(319, 288);
    vD_off[9] = *(float *)(&vD_tmp[9]);
    vD_tmp[10] = vD_on.data.range(351, 320);
    vD_off[10] = *(float *)(&vD_tmp[10]);
    vD_tmp[11] = vD_on.data.range(383, 352);
    vD_off[11] = *(float *)(&vD_tmp[11]);
    vD_tmp[12] = vD_on.data.range(415, 384);
    vD_off[12] = *(float *)(&vD_tmp[12]);
    vD_tmp[13] = vD_on.data.range(447, 416);
    vD_off[13] = *(float *)(&vD_tmp[13]);
    vD_tmp[14] = vD_on.data.range(479, 448);
    vD_off[14] = *(float *)(&vD_tmp[14]);
    vD_tmp[15] = vD_on.data.range(511, 480);
    vD_off[15] = *(float *)(&vD_tmp[15]);
    vD[i] = vD_off;
  }
}
void FT0_level0(float alpha, float beta,
                hls::stream<float16> &fifo_tmp_from_task1_to_task3,
                hls::stream<float16> &fifo_A_from_off_chip_to_S1,
                hls::stream<float16> &fifo_B_from_off_chip_to_S1,
                hls::stream<float16> &fifo_tmp_to_off_chip) {
#pragma HLS inline off
  float A_0[4][212];
  // FT0
#pragma HLS array_partition variable = A_0 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = A_0 cyclic factor = 4 dim = 2
  float A_1[4][212];
  // FT0
#pragma HLS array_partition variable = A_1 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = A_1 cyclic factor = 4 dim = 2
  float B[212][192];
#pragma HLS array_partition variable = B cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = B cyclic factor = 32 dim = 2
  read_B_FT0(B, fifo_B_from_off_chip_to_S1);
  read_A_FT0(A_0, fifo_A_from_off_chip_to_S1, 0);
  for (int i0 = 0; i0 < 45; i0++) {
    if (i0 % 2 == 0) {
      read_A_FT0(A_1, fifo_A_from_off_chip_to_S1, i0 + 1);
      FT0_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                 fifo_A_from_off_chip_to_S1, fifo_B_from_off_chip_to_S1,
                 fifo_tmp_to_off_chip, A_0, B, i0);
    } else if (i0 % 2 == 1) {
      read_A_FT0(A_0, fifo_A_from_off_chip_to_S1, i0 + 1);
      FT0_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                 fifo_A_from_off_chip_to_S1, fifo_B_from_off_chip_to_S1,
                 fifo_tmp_to_off_chip, A_1, B, i0);
    }
  }
}
void compute_FT0_level1(float alpha, float beta,
                        hls::stream<float16> &fifo_tmp_from_task1_to_task3,
                        hls::stream<float16> &fifo_A_from_off_chip_to_S1,
                        hls::stream<float16> &fifo_B_from_off_chip_to_S1,
                        hls::stream<float16> &fifo_tmp_to_off_chip,
                        float A[4][212], float B[212][192], int i0, int j0,
                        float tmp_0[4][32], float tmp_1[4][32]) {
#pragma HLS inline off
#pragma HLS dataflow
  task0_intra(alpha, beta, A, B, i0, tmp_0, j0);
  task1_intra(alpha, beta, A, B, i0, tmp_0, j0);
  write_tmp_FT0(tmp_1, fifo_tmp_from_task1_to_task3, j0 - 1, i0);
  write_tmp_FT0(tmp_1, fifo_tmp_to_off_chip, j0 - 1, i0);
}
void FT0_level1(float alpha, float beta,
                hls::stream<float16> &fifo_tmp_from_task1_to_task3,
                hls::stream<float16> &fifo_A_from_off_chip_to_S1,
                hls::stream<float16> &fifo_B_from_off_chip_to_S1,
                hls::stream<float16> &fifo_tmp_to_off_chip, float A[4][212],
                float B[212][192], int i0) {
#pragma HLS inline off
  float tmp_0[4][32];
  // FT0
#pragma HLS array_partition variable = tmp_0 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = tmp_0 cyclic factor = 32 dim = 2
  float tmp_1[4][32];
  // FT0
#pragma HLS array_partition variable = tmp_1 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = tmp_1 cyclic factor = 32 dim = 2
  for (int j0 = 0; j0 < 6; j0++) {

    if (j0 % 2 == 0) {
      //     task0_intra(alpha, beta, A, B, i0, tmp_0, j0);
      //     task1_intra(alpha, beta, A, B, i0, tmp_0, j0);
      //     write_tmp_FT0(tmp_1, fifo_tmp_from_task1_to_task3, j0-1, i0);
      //     write_tmp_FT0(tmp_1, fifo_tmp_to_off_chip, j0-1, i0);
      compute_FT0_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                         fifo_A_from_off_chip_to_S1, fifo_B_from_off_chip_to_S1,
                         fifo_tmp_to_off_chip, A, B, i0, j0, tmp_0, tmp_1);
    } else if (j0 % 2 == 1) {
      //     task0_intra(alpha, beta, A, B, i0, tmp_1, j0);
      //     task1_intra(alpha, beta, A, B, i0, tmp_1, j0);
      //     write_tmp_FT0(tmp_0, fifo_tmp_from_task1_to_task3, j0-1, i0);
      //     write_tmp_FT0(tmp_0, fifo_tmp_to_off_chip, j0-1, i0);
      compute_FT0_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                         fifo_A_from_off_chip_to_S1, fifo_B_from_off_chip_to_S1,
                         fifo_tmp_to_off_chip, A, B, i0, j0, tmp_1, tmp_0);
    }
  }
  write_tmp_FT0(tmp_1, fifo_tmp_from_task1_to_task3, 5, i0);
  write_tmp_FT0(tmp_1, fifo_tmp_to_off_chip, 5, i0);
}
void FT1_level0(float alpha, float beta,
                hls::stream<float16> &fifo_tmp_from_task1_to_task3,
                hls::stream<float16> &fifo_C_from_off_chip_to_S3,
                hls::stream<float16> &fifo_D_from_off_chip_to_S2,
                hls::stream<float16> &fifo_D_to_off_chip) {
#pragma HLS inline off
  float C_0[192][32];
  // FT1
#pragma HLS array_partition variable = C_0 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = C_0 cyclic factor = 32 dim = 2
  float C_1[192][32];
  // FT1
#pragma HLS array_partition variable = C_1 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = C_1 cyclic factor = 32 dim = 2
  float tmp_0[180][192];
#pragma HLS array_partition variable = tmp_0 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = tmp_0 cyclic factor = 4 dim = 2
  float tmp_1[180][192];
#pragma HLS array_partition variable = tmp_1 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = tmp_1 cyclic factor = 4 dim = 2
  float tmp_2[180][192];
#pragma HLS array_partition variable = tmp_2 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = tmp_2 cyclic factor = 4 dim = 2
  read_C_FT1(C_0, fifo_C_from_off_chip_to_S3, 0);
  for (int j0 = 0; j0 < 7; j0++) {
    if (j0 % 2 == 0) {
      read_C_FT1(C_1, fifo_C_from_off_chip_to_S3, j0 + 1);
      FT1_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                 fifo_C_from_off_chip_to_S3, fifo_D_from_off_chip_to_S2,
                 fifo_D_to_off_chip, C_0, tmp_0, tmp_1, tmp_2, j0);
    } else if (j0 % 2 == 1) {
      read_C_FT1(C_0, fifo_C_from_off_chip_to_S3, j0 + 1);
      FT1_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                 fifo_C_from_off_chip_to_S3, fifo_D_from_off_chip_to_S2,
                 fifo_D_to_off_chip, C_1, tmp_0, tmp_1, tmp_2, j0);
    }
  }
}
void compute_FT1_level1(float alpha, float beta,
                        hls::stream<float16> &fifo_tmp_from_task1_to_task3,
                        hls::stream<float16> &fifo_C_from_off_chip_to_S3,
                        hls::stream<float16> &fifo_D_from_off_chip_to_S2,
                        hls::stream<float16> &fifo_D_to_off_chip,
                        float C[192][32], int j0, int i0, float D_0[4][32],
                        float D_1[4][32], float D_2[4][32],
                        float tmp_0[180][192], float tmp_1[180][192],
                        float tmp_2[180][192]) {
#pragma HLS inline off
#pragma HLS dataflow
  read_D_FT1(D_0, fifo_D_from_off_chip_to_S2, i0 + 1, j0);
  read_tmp_FT1(tmp_0, fifo_tmp_from_task1_to_task3, i0 + 1, j0);
  task2_intra(alpha, beta, C, tmp_1, j0, D_1, i0);
  task3_intra(alpha, beta, C, tmp_1, j0, D_1, i0);
  write_D_FT1(D_2, fifo_D_to_off_chip, i0 - 1, j0);
}
void FT1_level1(float alpha, float beta,
                hls::stream<float16> &fifo_tmp_from_task1_to_task3,
                hls::stream<float16> &fifo_C_from_off_chip_to_S3,
                hls::stream<float16> &fifo_D_from_off_chip_to_S2,
                hls::stream<float16> &fifo_D_to_off_chip, float C[192][32],
                float tmp_0[180][192], float tmp_1[180][192],
                float tmp_2[180][192], int j0) {
#pragma HLS inline off
  float D_0[4][32];
  // FT1
#pragma HLS array_partition variable = D_0 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = D_0 cyclic factor = 32 dim = 2
  float D_1[4][32];
  // FT1
#pragma HLS array_partition variable = D_1 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = D_1 cyclic factor = 32 dim = 2
  float D_2[4][32];
  // FT1
#pragma HLS array_partition variable = D_2 cyclic factor = 4 dim = 1
#pragma HLS array_partition variable = D_2 cyclic factor = 32 dim = 2
  read_D_FT1(D_0, fifo_D_from_off_chip_to_S2, 0, j0);
  read_tmp_FT1(tmp_0, fifo_tmp_from_task1_to_task3, 0, j0);
  for (int i0 = 0; i0 < 45; i0++) {

    if (i0 % 3 == 0) {
      //     read_D_FT1(D_1, fifo_D_from_off_chip_to_S2, i0+1, j0);
      //     read_tmp_FT1(tmp_1, fifo_tmp_from_task1_to_task3, i0+1, j0);
      //     task2_intra(alpha, beta, C, tmp_0, j0, D_0, i0);
      //     task3_intra(alpha, beta, C, tmp_0, j0, D_0, i0);
      //     write_D_FT1(D_2, fifo_D_to_off_chip, i0-1, j0);
      compute_FT1_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                         fifo_C_from_off_chip_to_S3, fifo_D_from_off_chip_to_S2,
                         fifo_D_to_off_chip, C, j0, i0, D_1, D_0, D_2, tmp_1,
                         tmp_0, tmp_2);
    } else if (i0 % 3 == 1) {
      //     read_D_FT1(D_2, fifo_D_from_off_chip_to_S2, i0+1, j0);
      //     read_tmp_FT1(tmp_2, fifo_tmp_from_task1_to_task3, i0+1, j0);
      //     task2_intra(alpha, beta, C, tmp_1, j0, D_1, i0);
      //     task3_intra(alpha, beta, C, tmp_1, j0, D_1, i0);
      //     write_D_FT1(D_0, fifo_D_to_off_chip, i0-1, j0);
      compute_FT1_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                         fifo_C_from_off_chip_to_S3, fifo_D_from_off_chip_to_S2,
                         fifo_D_to_off_chip, C, j0, i0, D_2, D_1, D_0, tmp_2,
                         tmp_1, tmp_0);
    } else if (i0 % 3 == 2) {
      //     read_D_FT1(D_0, fifo_D_from_off_chip_to_S2, i0+1, j0);
      //     read_tmp_FT1(tmp_0, fifo_tmp_from_task1_to_task3, i0+1, j0);
      //     task2_intra(alpha, beta, C, tmp_2, j0, D_2, i0);
      //     task3_intra(alpha, beta, C, tmp_2, j0, D_2, i0);
      //     write_D_FT1(D_1, fifo_D_to_off_chip, i0-1, j0);
      compute_FT1_level1(alpha, beta, fifo_tmp_from_task1_to_task3,
                         fifo_C_from_off_chip_to_S3, fifo_D_from_off_chip_to_S2,
                         fifo_D_to_off_chip, C, j0, i0, D_0, D_2, D_1, tmp_0,
                         tmp_2, tmp_1);
    }
  }
  write_D_FT1(D_2, fifo_D_to_off_chip, 44, j0);
}
void task0_intra(float alpha, float beta, float A[4][212], float B[212][192],
                 int i0, float tmp[4][32], int j0) {
#pragma HLS inline off
  int i;
  int j;
  for (int i1 = 0; i1 < 4; i1++) {
#pragma HLS unroll
    for (int j1 = 0; j1 < 32; j1++) {
#pragma HLS unroll
      i = i0 * 4 + i1;
      j = j0 * 32 + j1;
      tmp[i1][j1] = 0.0;
    }
  }
}
void task1_intra(float alpha, float beta, float A[4][212], float B[212][192],
                 int i0, float tmp[4][32], int j0) {
#pragma HLS inline off
  int i;
  int j;
  int k;
  for (int k0 = 0; k0 < 53; k0++) {
#pragma HLS pipeline II = 2
    for (int i1 = 0; i1 < 4; i1++) {
#pragma HLS unroll
      for (int j1 = 0; j1 < 32; j1++) {
#pragma HLS unroll
        for (int k1 = 0; k1 < 4; k1++) {
#pragma HLS unroll
          i = i0 * 4 + i1;
          j = j0 * 32 + j1;
          k = k0 * 4 + k1;
          tmp[i1][j1] = tmp[i1][j1] + alpha * A[i1][k] * B[k][j];
        }
      }
    }
  }
}
void task2_intra(float alpha, float beta, float C[192][32], float tmp[180][192],
                 int j0, float D[4][32], int i0) {
#pragma HLS inline off
  int j;
  int i;
  for (int j1 = 0; j1 < 32; j1++) {
#pragma HLS unroll
    for (int i1 = 0; i1 < 4; i1++) {
#pragma HLS unroll
      j = j0 * 32 + j1;
      i = i0 * 4 + i1;
      D[i1][j1] = D[i1][j1] * beta;
    }
  }
}
void task3_intra(float alpha, float beta, float C[192][32], float tmp[180][192],
                 int j0, float D[4][32], int i0) {
#pragma HLS inline off
  int j;
  int i;
  int k;
  for (int k0 = 0; k0 < 48; k0++) {
#pragma HLS pipeline II = 2
    for (int j1 = 0; j1 < 32; j1++) {
#pragma HLS unroll
      for (int i1 = 0; i1 < 4; i1++) {
#pragma HLS unroll
        for (int k1 = 0; k1 < 4; k1++) {
#pragma HLS unroll
          j = j0 * 32 + j1;
          i = i0 * 4 + i1;
          k = k0 * 4 + k1;
          D[i1][j1] = D[i1][j1] + tmp[i][k] * C[k][j1];
        }
      }
    }
  }
}
void read_B_FT0(float B[212][192],
                hls::stream<float16> &fifo_B_from_off_chip_to_S1) {
#pragma HLS inline off
  for (int d0 = 0; d0 < 212; d0++) {
    for (int d1 = 0; d1 < 192; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_B_from_off_chip_to_S1.read();
      B[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      B[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      B[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      B[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      B[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      B[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      B[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      B[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      B[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      B[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      B[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      B[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      B[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      B[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      B[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      B[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}
void read_B_FT0(
    float B[212][192],
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_B_from_off_chip_to_S1) {
#pragma HLS inline off
  for (int d0 = 0; d0 < 212; d0++) {
    for (int d1 = 0; d1 < 192; d1 += 16) {
#pragma HLS pipeline II = 1
      ap_axiu<512, 0, 0, 0> tmp_fifo = fifo_B_from_off_chip_to_S1.read();
      uint32_t tmp_0 = tmp_fifo.data.range(31, 0);
      B[d0 + 0][d1 + 0 + 0] = *(float *)(&tmp_0);
      uint32_t tmp_1 = tmp_fifo.data.range(63, 32);
      B[d0 + 0][d1 + 0 + 1] = *(float *)(&tmp_1);
      uint32_t tmp_2 = tmp_fifo.data.range(95, 64);
      B[d0 + 0][d1 + 0 + 2] = *(float *)(&tmp_2);
      uint32_t tmp_3 = tmp_fifo.data.range(127, 96);
      B[d0 + 0][d1 + 0 + 3] = *(float *)(&tmp_3);
      uint32_t tmp_4 = tmp_fifo.data.range(159, 128);
      B[d0 + 0][d1 + 0 + 4] = *(float *)(&tmp_4);
      uint32_t tmp_5 = tmp_fifo.data.range(191, 160);
      B[d0 + 0][d1 + 0 + 5] = *(float *)(&tmp_5);
      uint32_t tmp_6 = tmp_fifo.data.range(223, 192);
      B[d0 + 0][d1 + 0 + 6] = *(float *)(&tmp_6);
      uint32_t tmp_7 = tmp_fifo.data.range(255, 224);
      B[d0 + 0][d1 + 0 + 7] = *(float *)(&tmp_7);
      uint32_t tmp_8 = tmp_fifo.data.range(287, 256);
      B[d0 + 0][d1 + 0 + 8] = *(float *)(&tmp_8);
      uint32_t tmp_9 = tmp_fifo.data.range(319, 288);
      B[d0 + 0][d1 + 0 + 9] = *(float *)(&tmp_9);
      uint32_t tmp_10 = tmp_fifo.data.range(351, 320);
      B[d0 + 0][d1 + 0 + 10] = *(float *)(&tmp_10);
      uint32_t tmp_11 = tmp_fifo.data.range(383, 352);
      B[d0 + 0][d1 + 0 + 11] = *(float *)(&tmp_11);
      uint32_t tmp_12 = tmp_fifo.data.range(415, 384);
      B[d0 + 0][d1 + 0 + 12] = *(float *)(&tmp_12);
      uint32_t tmp_13 = tmp_fifo.data.range(447, 416);
      B[d0 + 0][d1 + 0 + 13] = *(float *)(&tmp_13);
      uint32_t tmp_14 = tmp_fifo.data.range(479, 448);
      B[d0 + 0][d1 + 0 + 14] = *(float *)(&tmp_14);
      uint32_t tmp_15 = tmp_fifo.data.range(511, 480);
      B[d0 + 0][d1 + 0 + 15] = *(float *)(&tmp_15);
    }
  }
}
void read_A_FT0(float A[4][212],
                hls::stream<float16> &fifo_A_from_off_chip_to_S1, int i0) {
#pragma HLS inline off
  if (i0 >= 45) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 212; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_A_from_off_chip_to_S1.read();
      if (d1 + 0 < 212)
        A[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      if (d1 + 1 < 212)
        A[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      if (d1 + 2 < 212)
        A[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      if (d1 + 3 < 212)
        A[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      if (d1 + 4 < 212)
        A[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      if (d1 + 5 < 212)
        A[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      if (d1 + 6 < 212)
        A[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      if (d1 + 7 < 212)
        A[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      if (d1 + 8 < 212)
        A[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      if (d1 + 9 < 212)
        A[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      if (d1 + 10 < 212)
        A[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      if (d1 + 11 < 212)
        A[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      if (d1 + 12 < 212)
        A[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      if (d1 + 13 < 212)
        A[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      if (d1 + 14 < 212)
        A[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      if (d1 + 15 < 212)
        A[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}
void read_A_FT0(float A[4][212],
                hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_A_from_off_chip_to_S1,
                int i0) {
#pragma HLS inline off
  if (i0 >= 45) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 212; d1 += 16) {
#pragma HLS pipeline II = 1
      ap_axiu<512, 0, 0, 0> tmp_fifo = fifo_A_from_off_chip_to_S1.read();
      if (d1 + 0 < 212) {
        uint32_t tmp_0 = tmp_fifo.data.range(31, 0);
        A[d0 + 0][d1 + 0 + 0] = *(float *)(&tmp_0);
      }
      if (d1 + 1 < 212) {
        uint32_t tmp_1 = tmp_fifo.data.range(63, 32);
        A[d0 + 0][d1 + 0 + 1] = *(float *)(&tmp_1);
      }
      if (d1 + 2 < 212) {
        uint32_t tmp_2 = tmp_fifo.data.range(95, 64);
        A[d0 + 0][d1 + 0 + 2] = *(float *)(&tmp_2);
      }
      if (d1 + 3 < 212) {
        uint32_t tmp_3 = tmp_fifo.data.range(127, 96);
        A[d0 + 0][d1 + 0 + 3] = *(float *)(&tmp_3);
      }
      if (d1 + 4 < 212) {
        uint32_t tmp_4 = tmp_fifo.data.range(159, 128);
        A[d0 + 0][d1 + 0 + 4] = *(float *)(&tmp_4);
      }
      if (d1 + 5 < 212) {
        uint32_t tmp_5 = tmp_fifo.data.range(191, 160);
        A[d0 + 0][d1 + 0 + 5] = *(float *)(&tmp_5);
      }
      if (d1 + 6 < 212) {
        uint32_t tmp_6 = tmp_fifo.data.range(223, 192);
        A[d0 + 0][d1 + 0 + 6] = *(float *)(&tmp_6);
      }
      if (d1 + 7 < 212) {
        uint32_t tmp_7 = tmp_fifo.data.range(255, 224);
        A[d0 + 0][d1 + 0 + 7] = *(float *)(&tmp_7);
      }
      if (d1 + 8 < 212) {
        uint32_t tmp_8 = tmp_fifo.data.range(287, 256);
        A[d0 + 0][d1 + 0 + 8] = *(float *)(&tmp_8);
      }
      if (d1 + 9 < 212) {
        uint32_t tmp_9 = tmp_fifo.data.range(319, 288);
        A[d0 + 0][d1 + 0 + 9] = *(float *)(&tmp_9);
      }
      if (d1 + 10 < 212) {
        uint32_t tmp_10 = tmp_fifo.data.range(351, 320);
        A[d0 + 0][d1 + 0 + 10] = *(float *)(&tmp_10);
      }
      if (d1 + 11 < 212) {
        uint32_t tmp_11 = tmp_fifo.data.range(383, 352);
        A[d0 + 0][d1 + 0 + 11] = *(float *)(&tmp_11);
      }
      if (d1 + 12 < 212) {
        uint32_t tmp_12 = tmp_fifo.data.range(415, 384);
        A[d0 + 0][d1 + 0 + 12] = *(float *)(&tmp_12);
      }
      if (d1 + 13 < 212) {
        uint32_t tmp_13 = tmp_fifo.data.range(447, 416);
        A[d0 + 0][d1 + 0 + 13] = *(float *)(&tmp_13);
      }
      if (d1 + 14 < 212) {
        uint32_t tmp_14 = tmp_fifo.data.range(479, 448);
        A[d0 + 0][d1 + 0 + 14] = *(float *)(&tmp_14);
      }
      if (d1 + 15 < 212) {
        uint32_t tmp_15 = tmp_fifo.data.range(511, 480);
        A[d0 + 0][d1 + 0 + 15] = *(float *)(&tmp_15);
      }
    }
  }
}
void read_C_FT1(float C[192][32],
                hls::stream<float16> &fifo_C_from_off_chip_to_S3, int j0) {
#pragma HLS inline off
  if (j0 >= 7) {
    return;
  }
  for (int d0 = 0; d0 < 192; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_C_from_off_chip_to_S3.read();
      C[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      C[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      C[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      C[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      C[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      C[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      C[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      C[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      C[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      C[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      C[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      C[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      C[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      C[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      C[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      C[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}
void read_C_FT1(float C[192][32],
                hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_C_from_off_chip_to_S3,
                int j0) {
#pragma HLS inline off
  if (j0 >= 7) {
    return;
  }
  for (int d0 = 0; d0 < 192; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      ap_axiu<512, 0, 0, 0> tmp_fifo = fifo_C_from_off_chip_to_S3.read();
      uint32_t tmp_0 = tmp_fifo.data.range(31, 0);
      C[d0 + 0][d1 + 0 + 0] = *(float *)(&tmp_0);
      uint32_t tmp_1 = tmp_fifo.data.range(63, 32);
      C[d0 + 0][d1 + 0 + 1] = *(float *)(&tmp_1);
      uint32_t tmp_2 = tmp_fifo.data.range(95, 64);
      C[d0 + 0][d1 + 0 + 2] = *(float *)(&tmp_2);
      uint32_t tmp_3 = tmp_fifo.data.range(127, 96);
      C[d0 + 0][d1 + 0 + 3] = *(float *)(&tmp_3);
      uint32_t tmp_4 = tmp_fifo.data.range(159, 128);
      C[d0 + 0][d1 + 0 + 4] = *(float *)(&tmp_4);
      uint32_t tmp_5 = tmp_fifo.data.range(191, 160);
      C[d0 + 0][d1 + 0 + 5] = *(float *)(&tmp_5);
      uint32_t tmp_6 = tmp_fifo.data.range(223, 192);
      C[d0 + 0][d1 + 0 + 6] = *(float *)(&tmp_6);
      uint32_t tmp_7 = tmp_fifo.data.range(255, 224);
      C[d0 + 0][d1 + 0 + 7] = *(float *)(&tmp_7);
      uint32_t tmp_8 = tmp_fifo.data.range(287, 256);
      C[d0 + 0][d1 + 0 + 8] = *(float *)(&tmp_8);
      uint32_t tmp_9 = tmp_fifo.data.range(319, 288);
      C[d0 + 0][d1 + 0 + 9] = *(float *)(&tmp_9);
      uint32_t tmp_10 = tmp_fifo.data.range(351, 320);
      C[d0 + 0][d1 + 0 + 10] = *(float *)(&tmp_10);
      uint32_t tmp_11 = tmp_fifo.data.range(383, 352);
      C[d0 + 0][d1 + 0 + 11] = *(float *)(&tmp_11);
      uint32_t tmp_12 = tmp_fifo.data.range(415, 384);
      C[d0 + 0][d1 + 0 + 12] = *(float *)(&tmp_12);
      uint32_t tmp_13 = tmp_fifo.data.range(447, 416);
      C[d0 + 0][d1 + 0 + 13] = *(float *)(&tmp_13);
      uint32_t tmp_14 = tmp_fifo.data.range(479, 448);
      C[d0 + 0][d1 + 0 + 14] = *(float *)(&tmp_14);
      uint32_t tmp_15 = tmp_fifo.data.range(511, 480);
      C[d0 + 0][d1 + 0 + 15] = *(float *)(&tmp_15);
    }
  }
}
void read_D_FT1(float D[4][32],
                hls::stream<float16> &fifo_D_from_off_chip_to_S2, int i0,
                int j0) {
#pragma HLS inline off
  if (j0 >= 7 || i0 >= 45) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_D_from_off_chip_to_S2.read();
      D[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      D[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      D[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      D[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      D[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      D[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      D[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      D[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      D[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      D[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      D[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      D[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      D[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      D[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      D[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      D[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}
void read_D_FT1(float D[4][32],
                hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_D_from_off_chip_to_S2,
                int i0, int j0) {
#pragma HLS inline off
  if (j0 >= 7 || i0 >= 45) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      ap_axiu<512, 0, 0, 0> tmp_fifo = fifo_D_from_off_chip_to_S2.read();
      uint32_t tmp_0 = tmp_fifo.data.range(31, 0);
      D[d0 + 0][d1 + 0 + 0] = *(float *)(&tmp_0);
      uint32_t tmp_1 = tmp_fifo.data.range(63, 32);
      D[d0 + 0][d1 + 0 + 1] = *(float *)(&tmp_1);
      uint32_t tmp_2 = tmp_fifo.data.range(95, 64);
      D[d0 + 0][d1 + 0 + 2] = *(float *)(&tmp_2);
      uint32_t tmp_3 = tmp_fifo.data.range(127, 96);
      D[d0 + 0][d1 + 0 + 3] = *(float *)(&tmp_3);
      uint32_t tmp_4 = tmp_fifo.data.range(159, 128);
      D[d0 + 0][d1 + 0 + 4] = *(float *)(&tmp_4);
      uint32_t tmp_5 = tmp_fifo.data.range(191, 160);
      D[d0 + 0][d1 + 0 + 5] = *(float *)(&tmp_5);
      uint32_t tmp_6 = tmp_fifo.data.range(223, 192);
      D[d0 + 0][d1 + 0 + 6] = *(float *)(&tmp_6);
      uint32_t tmp_7 = tmp_fifo.data.range(255, 224);
      D[d0 + 0][d1 + 0 + 7] = *(float *)(&tmp_7);
      uint32_t tmp_8 = tmp_fifo.data.range(287, 256);
      D[d0 + 0][d1 + 0 + 8] = *(float *)(&tmp_8);
      uint32_t tmp_9 = tmp_fifo.data.range(319, 288);
      D[d0 + 0][d1 + 0 + 9] = *(float *)(&tmp_9);
      uint32_t tmp_10 = tmp_fifo.data.range(351, 320);
      D[d0 + 0][d1 + 0 + 10] = *(float *)(&tmp_10);
      uint32_t tmp_11 = tmp_fifo.data.range(383, 352);
      D[d0 + 0][d1 + 0 + 11] = *(float *)(&tmp_11);
      uint32_t tmp_12 = tmp_fifo.data.range(415, 384);
      D[d0 + 0][d1 + 0 + 12] = *(float *)(&tmp_12);
      uint32_t tmp_13 = tmp_fifo.data.range(447, 416);
      D[d0 + 0][d1 + 0 + 13] = *(float *)(&tmp_13);
      uint32_t tmp_14 = tmp_fifo.data.range(479, 448);
      D[d0 + 0][d1 + 0 + 14] = *(float *)(&tmp_14);
      uint32_t tmp_15 = tmp_fifo.data.range(511, 480);
      D[d0 + 0][d1 + 0 + 15] = *(float *)(&tmp_15);
    }
  }
}
void read_tmp_FT1(float tmp[180][192],
                  hls::stream<float16> &fifo_tmp_from_task1_to_task3, int i0,
                  int j0) {
#pragma HLS inline off
  if (j0 > 0 || i0 >= 45) {
    return;
  }
  for (int d1_0 = 0; d1_0 < 6; d1_0++) {

    for (int d0_1 = 0; d0_1 < 4; d0_1++) {

      for (int d1_1 = 0; d1_1 < 32; d1_1 += 16) {

        int d0 = d0_1;
        int d1 = d1_0 * 32 + d1_1;
        float16 tmp_fifo = fifo_tmp_from_task1_to_task3.read();
        if (d1 + 0 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 0] = tmp_fifo[0];
        if (d1 + 1 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 1] = tmp_fifo[1];
        if (d1 + 2 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 2] = tmp_fifo[2];
        if (d1 + 3 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 3] = tmp_fifo[3];
        if (d1 + 4 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 4] = tmp_fifo[4];
        if (d1 + 5 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 5] = tmp_fifo[5];
        if (d1 + 6 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 6] = tmp_fifo[6];
        if (d1 + 7 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 7] = tmp_fifo[7];
        if (d1 + 8 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 8] = tmp_fifo[8];
        if (d1 + 9 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 9] = tmp_fifo[9];
        if (d1 + 10 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 10] = tmp_fifo[10];
        if (d1 + 11 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 11] = tmp_fifo[11];
        if (d1 + 12 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 12] = tmp_fifo[12];
        if (d1 + 13 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 13] = tmp_fifo[13];
        if (d1 + 14 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 14] = tmp_fifo[14];
        if (d1 + 15 < 192)
          tmp[d0 + i0 * 4][d1 + 0 + 15] = tmp_fifo[15];
      }
    }
  }
}
void read_tmp_FT1(
    float tmp[180][192],
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_tmp_from_task1_to_task3, int i0,
    int j0) {
#pragma HLS inline off
  if (j0 > 0 || i0 >= 45) {
    return;
  }
  for (int d1_0 = 0; d1_0 < 6; d1_0++) {

    for (int d0_1 = 0; d0_1 < 4; d0_1++) {

      for (int d1_1 = 0; d1_1 < 32; d1_1 += 16) {

        int d0 = d0_1;
        int d1 = d1_0 * 32 + d1_1;
        ap_axiu<512, 0, 0, 0> tmp_fifo = fifo_tmp_from_task1_to_task3.read();
        if (d1 + 0 < 192) {
          uint32_t tmp_0 = tmp_fifo.data.range(31, 0);
          tmp[d0 + i0 * 4][d1 + 0 + 0] = *(float *)(&tmp_0);
        }
        if (d1 + 1 < 192) {
          uint32_t tmp_1 = tmp_fifo.data.range(63, 32);
          tmp[d0 + i0 * 4][d1 + 0 + 1] = *(float *)(&tmp_1);
        }
        if (d1 + 2 < 192) {
          uint32_t tmp_2 = tmp_fifo.data.range(95, 64);
          tmp[d0 + i0 * 4][d1 + 0 + 2] = *(float *)(&tmp_2);
        }
        if (d1 + 3 < 192) {
          uint32_t tmp_3 = tmp_fifo.data.range(127, 96);
          tmp[d0 + i0 * 4][d1 + 0 + 3] = *(float *)(&tmp_3);
        }
        if (d1 + 4 < 192) {
          uint32_t tmp_4 = tmp_fifo.data.range(159, 128);
          tmp[d0 + i0 * 4][d1 + 0 + 4] = *(float *)(&tmp_4);
        }
        if (d1 + 5 < 192) {
          uint32_t tmp_5 = tmp_fifo.data.range(191, 160);
          tmp[d0 + i0 * 4][d1 + 0 + 5] = *(float *)(&tmp_5);
        }
        if (d1 + 6 < 192) {
          uint32_t tmp_6 = tmp_fifo.data.range(223, 192);
          tmp[d0 + i0 * 4][d1 + 0 + 6] = *(float *)(&tmp_6);
        }
        if (d1 + 7 < 192) {
          uint32_t tmp_7 = tmp_fifo.data.range(255, 224);
          tmp[d0 + i0 * 4][d1 + 0 + 7] = *(float *)(&tmp_7);
        }
        if (d1 + 8 < 192) {
          uint32_t tmp_8 = tmp_fifo.data.range(287, 256);
          tmp[d0 + i0 * 4][d1 + 0 + 8] = *(float *)(&tmp_8);
        }
        if (d1 + 9 < 192) {
          uint32_t tmp_9 = tmp_fifo.data.range(319, 288);
          tmp[d0 + i0 * 4][d1 + 0 + 9] = *(float *)(&tmp_9);
        }
        if (d1 + 10 < 192) {
          uint32_t tmp_10 = tmp_fifo.data.range(351, 320);
          tmp[d0 + i0 * 4][d1 + 0 + 10] = *(float *)(&tmp_10);
        }
        if (d1 + 11 < 192) {
          uint32_t tmp_11 = tmp_fifo.data.range(383, 352);
          tmp[d0 + i0 * 4][d1 + 0 + 11] = *(float *)(&tmp_11);
        }
        if (d1 + 12 < 192) {
          uint32_t tmp_12 = tmp_fifo.data.range(415, 384);
          tmp[d0 + i0 * 4][d1 + 0 + 12] = *(float *)(&tmp_12);
        }
        if (d1 + 13 < 192) {
          uint32_t tmp_13 = tmp_fifo.data.range(447, 416);
          tmp[d0 + i0 * 4][d1 + 0 + 13] = *(float *)(&tmp_13);
        }
        if (d1 + 14 < 192) {
          uint32_t tmp_14 = tmp_fifo.data.range(479, 448);
          tmp[d0 + i0 * 4][d1 + 0 + 14] = *(float *)(&tmp_14);
        }
        if (d1 + 15 < 192) {
          uint32_t tmp_15 = tmp_fifo.data.range(511, 480);
          tmp[d0 + i0 * 4][d1 + 0 + 15] = *(float *)(&tmp_15);
        }
      }
    }
  }
}
void write_tmp_FT0(float tmp[4][32],
                   hls::stream<float16> &fifo_tmp_from_task1_to_task3, int j0,
                   int i0) {
#pragma HLS inline off
  if (j0 < 0 || i0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo;
      tmp_fifo[0] = tmp[d0 + 0][d1 + 0 + 0];
      tmp_fifo[1] = tmp[d0 + 0][d1 + 0 + 1];
      tmp_fifo[2] = tmp[d0 + 0][d1 + 0 + 2];
      tmp_fifo[3] = tmp[d0 + 0][d1 + 0 + 3];
      tmp_fifo[4] = tmp[d0 + 0][d1 + 0 + 4];
      tmp_fifo[5] = tmp[d0 + 0][d1 + 0 + 5];
      tmp_fifo[6] = tmp[d0 + 0][d1 + 0 + 6];
      tmp_fifo[7] = tmp[d0 + 0][d1 + 0 + 7];
      tmp_fifo[8] = tmp[d0 + 0][d1 + 0 + 8];
      tmp_fifo[9] = tmp[d0 + 0][d1 + 0 + 9];
      tmp_fifo[10] = tmp[d0 + 0][d1 + 0 + 10];
      tmp_fifo[11] = tmp[d0 + 0][d1 + 0 + 11];
      tmp_fifo[12] = tmp[d0 + 0][d1 + 0 + 12];
      tmp_fifo[13] = tmp[d0 + 0][d1 + 0 + 13];
      tmp_fifo[14] = tmp[d0 + 0][d1 + 0 + 14];
      tmp_fifo[15] = tmp[d0 + 0][d1 + 0 + 15];
      fifo_tmp_from_task1_to_task3.write(tmp_fifo);
    }
  }
}
void write_tmp_FT0(
    float tmp[4][32],
    hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_tmp_from_task1_to_task3, int j0,
    int i0) {
#pragma HLS inline off
  if (j0 < 0 || i0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      ap_axiu<512, 0, 0, 0> tmp_fifo;
      float tmp_0 = tmp[d0 + 0][d1 + 0 + 0];
      tmp_fifo.data.range(31, 0) = *(uint32_t *)(&tmp_0);
      float tmp_1 = tmp[d0 + 0][d1 + 0 + 1];
      tmp_fifo.data.range(63, 32) = *(uint32_t *)(&tmp_1);
      float tmp_2 = tmp[d0 + 0][d1 + 0 + 2];
      tmp_fifo.data.range(95, 64) = *(uint32_t *)(&tmp_2);
      float tmp_3 = tmp[d0 + 0][d1 + 0 + 3];
      tmp_fifo.data.range(127, 96) = *(uint32_t *)(&tmp_3);
      float tmp_4 = tmp[d0 + 0][d1 + 0 + 4];
      tmp_fifo.data.range(159, 128) = *(uint32_t *)(&tmp_4);
      float tmp_5 = tmp[d0 + 0][d1 + 0 + 5];
      tmp_fifo.data.range(191, 160) = *(uint32_t *)(&tmp_5);
      float tmp_6 = tmp[d0 + 0][d1 + 0 + 6];
      tmp_fifo.data.range(223, 192) = *(uint32_t *)(&tmp_6);
      float tmp_7 = tmp[d0 + 0][d1 + 0 + 7];
      tmp_fifo.data.range(255, 224) = *(uint32_t *)(&tmp_7);
      float tmp_8 = tmp[d0 + 0][d1 + 0 + 8];
      tmp_fifo.data.range(287, 256) = *(uint32_t *)(&tmp_8);
      float tmp_9 = tmp[d0 + 0][d1 + 0 + 9];
      tmp_fifo.data.range(319, 288) = *(uint32_t *)(&tmp_9);
      float tmp_10 = tmp[d0 + 0][d1 + 0 + 10];
      tmp_fifo.data.range(351, 320) = *(uint32_t *)(&tmp_10);
      float tmp_11 = tmp[d0 + 0][d1 + 0 + 11];
      tmp_fifo.data.range(383, 352) = *(uint32_t *)(&tmp_11);
      float tmp_12 = tmp[d0 + 0][d1 + 0 + 12];
      tmp_fifo.data.range(415, 384) = *(uint32_t *)(&tmp_12);
      float tmp_13 = tmp[d0 + 0][d1 + 0 + 13];
      tmp_fifo.data.range(447, 416) = *(uint32_t *)(&tmp_13);
      float tmp_14 = tmp[d0 + 0][d1 + 0 + 14];
      tmp_fifo.data.range(479, 448) = *(uint32_t *)(&tmp_14);
      float tmp_15 = tmp[d0 + 0][d1 + 0 + 15];
      tmp_fifo.data.range(511, 480) = *(uint32_t *)(&tmp_15);
      fifo_tmp_from_task1_to_task3.write(tmp_fifo);
    }
  }
}
void write_D_FT1(float D[4][32], hls::stream<float16> &fifo_D_to_off_chip,
                 int i0, int j0) {
#pragma HLS inline off
  if (i0 < 0 || j0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo;
      tmp_fifo[0] = D[d0 + 0][d1 + 0 + 0];
      tmp_fifo[1] = D[d0 + 0][d1 + 0 + 1];
      tmp_fifo[2] = D[d0 + 0][d1 + 0 + 2];
      tmp_fifo[3] = D[d0 + 0][d1 + 0 + 3];
      tmp_fifo[4] = D[d0 + 0][d1 + 0 + 4];
      tmp_fifo[5] = D[d0 + 0][d1 + 0 + 5];
      tmp_fifo[6] = D[d0 + 0][d1 + 0 + 6];
      tmp_fifo[7] = D[d0 + 0][d1 + 0 + 7];
      tmp_fifo[8] = D[d0 + 0][d1 + 0 + 8];
      tmp_fifo[9] = D[d0 + 0][d1 + 0 + 9];
      tmp_fifo[10] = D[d0 + 0][d1 + 0 + 10];
      tmp_fifo[11] = D[d0 + 0][d1 + 0 + 11];
      tmp_fifo[12] = D[d0 + 0][d1 + 0 + 12];
      tmp_fifo[13] = D[d0 + 0][d1 + 0 + 13];
      tmp_fifo[14] = D[d0 + 0][d1 + 0 + 14];
      tmp_fifo[15] = D[d0 + 0][d1 + 0 + 15];
      fifo_D_to_off_chip.write(tmp_fifo);
    }
  }
}
void write_D_FT1(float D[4][32],
                 hls::stream<ap_axiu<512, 0, 0, 0>> &fifo_D_to_off_chip, int i0,
                 int j0) {
#pragma HLS inline off
  if (i0 < 0 || j0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 4; d0++) {
    for (int d1 = 0; d1 < 32; d1 += 16) {
#pragma HLS pipeline II = 1
      ap_axiu<512, 0, 0, 0> tmp_fifo;
      float tmp_0 = D[d0 + 0][d1 + 0 + 0];
      tmp_fifo.data.range(31, 0) = *(uint32_t *)(&tmp_0);
      float tmp_1 = D[d0 + 0][d1 + 0 + 1];
      tmp_fifo.data.range(63, 32) = *(uint32_t *)(&tmp_1);
      float tmp_2 = D[d0 + 0][d1 + 0 + 2];
      tmp_fifo.data.range(95, 64) = *(uint32_t *)(&tmp_2);
      float tmp_3 = D[d0 + 0][d1 + 0 + 3];
      tmp_fifo.data.range(127, 96) = *(uint32_t *)(&tmp_3);
      float tmp_4 = D[d0 + 0][d1 + 0 + 4];
      tmp_fifo.data.range(159, 128) = *(uint32_t *)(&tmp_4);
      float tmp_5 = D[d0 + 0][d1 + 0 + 5];
      tmp_fifo.data.range(191, 160) = *(uint32_t *)(&tmp_5);
      float tmp_6 = D[d0 + 0][d1 + 0 + 6];
      tmp_fifo.data.range(223, 192) = *(uint32_t *)(&tmp_6);
      float tmp_7 = D[d0 + 0][d1 + 0 + 7];
      tmp_fifo.data.range(255, 224) = *(uint32_t *)(&tmp_7);
      float tmp_8 = D[d0 + 0][d1 + 0 + 8];
      tmp_fifo.data.range(287, 256) = *(uint32_t *)(&tmp_8);
      float tmp_9 = D[d0 + 0][d1 + 0 + 9];
      tmp_fifo.data.range(319, 288) = *(uint32_t *)(&tmp_9);
      float tmp_10 = D[d0 + 0][d1 + 0 + 10];
      tmp_fifo.data.range(351, 320) = *(uint32_t *)(&tmp_10);
      float tmp_11 = D[d0 + 0][d1 + 0 + 11];
      tmp_fifo.data.range(383, 352) = *(uint32_t *)(&tmp_11);
      float tmp_12 = D[d0 + 0][d1 + 0 + 12];
      tmp_fifo.data.range(415, 384) = *(uint32_t *)(&tmp_12);
      float tmp_13 = D[d0 + 0][d1 + 0 + 13];
      tmp_fifo.data.range(447, 416) = *(uint32_t *)(&tmp_13);
      float tmp_14 = D[d0 + 0][d1 + 0 + 14];
      tmp_fifo.data.range(479, 448) = *(uint32_t *)(&tmp_14);
      float tmp_15 = D[d0 + 0][d1 + 0 + 15];
      tmp_fifo.data.range(511, 480) = *(uint32_t *)(&tmp_15);
      fifo_D_to_off_chip.write(tmp_fifo);
    }
  }
}

void kernel_nlp_slr0(float alpha, float beta, float16 vtmp_for_task1[2160],
                     float16 vA_for_task1[2520], float16 vB_for_task1[2544],
                     float16 vD_for_task2[2520], float16 vC_for_task3[2688]) {
#pragma HLS INTERFACE m_axi port = alpha offset = slave bundle = kernel_alpha
#pragma HLS INTERFACE m_axi port = beta offset = slave bundle = kernel_beta
#pragma HLS INTERFACE m_axi port = vtmp_for_task1 offset = slave bundle =      \
    kernel_vtmp_for_task1
#pragma HLS INTERFACE m_axi port = vA_for_task1 offset = slave bundle =        \
    kernel_vA_for_task1
#pragma HLS INTERFACE m_axi port = vB_for_task1 offset = slave bundle =        \
    kernel_vB_for_task1
#pragma HLS INTERFACE m_axi port = vD_for_task2 offset = slave bundle =        \
    kernel_vD_for_task2
#pragma HLS INTERFACE m_axi port = vC_for_task3 offset = slave bundle =        \
    kernel_vC_for_task3
#pragma HLS INTERFACE s_axilite port = alpha bundle = control
#pragma HLS INTERFACE s_axilite port = beta bundle = control
#pragma HLS INTERFACE s_axilite port = vtmp_for_task1 bundle = control
#pragma HLS INTERFACE s_axilite port = vA_for_task1 bundle = control
#pragma HLS INTERFACE s_axilite port = vB_for_task1 bundle = control
#pragma HLS INTERFACE s_axilite port = vD_for_task2 bundle = control
#pragma HLS INTERFACE s_axilite port = vC_for_task3 bundle = control
#pragma HLS DATA_PACK VARIABLE = alpha
#pragma HLS DATA_PACK VARIABLE = beta
#pragma HLS DATA_PACK VARIABLE = vtmp_for_task1
#pragma HLS DATA_PACK VARIABLE = vA_for_task1
#pragma HLS DATA_PACK VARIABLE = vB_for_task1
#pragma HLS DATA_PACK VARIABLE = vD_for_task2
#pragma HLS DATA_PACK VARIABLE = vC_for_task3
#pragma HLS INTERFACE s_axilite port = return bundle = control
#pragma HLS dataflow
  hls::stream<float16> fifo_tmp_from_task1_to_task3;
#pragma HLS stream variable = fifo_tmp_from_task1_to_task3 depth = 1024
  hls::stream<float16> fifo_D_to_off_chip;
#pragma HLS stream variable = fifo_D_to_off_chip depth = 1024
  hls::stream<float16> fifo_tmp_to_off_chip;
#pragma HLS stream variable = fifo_tmp_to_off_chip depth = 1024
  hls::stream<float16> fifo_B_from_off_chip_to_S1;
#pragma HLS stream variable = fifo_B_from_off_chip_to_S1 depth = 1024
  hls::stream<float16> fifo_A_from_off_chip_to_S1;
#pragma HLS stream variable = fifo_A_from_off_chip_to_S1 depth = 1024
  hls::stream<float16> fifo_D_from_off_chip_to_S2;
#pragma HLS stream variable = fifo_D_from_off_chip_to_S2 depth = 1024
  hls::stream<float16> fifo_C_from_off_chip_to_S3;
#pragma HLS stream variable = fifo_C_from_off_chip_to_S3 depth = 1024
  load_vC_for_task3(fifo_C_from_off_chip_to_S3, vC_for_task3);
  load_vD_for_task2(fifo_D_from_off_chip_to_S2, vD_for_task2);
  load_vA_for_task1(fifo_A_from_off_chip_to_S1, vA_for_task1);
  load_vB_for_task1(fifo_B_from_off_chip_to_S1, vB_for_task1);
  FT0_level0(alpha, beta, fifo_tmp_from_task1_to_task3,
             fifo_A_from_off_chip_to_S1, fifo_B_from_off_chip_to_S1,
             fifo_tmp_to_off_chip);
  FT1_level0(alpha, beta, fifo_tmp_from_task1_to_task3,
             fifo_C_from_off_chip_to_S3, fifo_D_from_off_chip_to_S2,
             fifo_D_to_off_chip);
  store_vtmp_for_task1(fifo_tmp_to_off_chip, vtmp_for_task1);
  store_vD_for_task2(fifo_D_to_off_chip, vD_for_task2);
}
