#include "output_2.h"

#define READ_RANGE(Arr, data_size, l)                                          \
  (Arr.data.range((data_size) * (l) + (data_size) - 1, (data_size) * (l)))

/****************************************************
 This file was automatically generated by Prometheus
****************************************************/
void load_vB_for_task0(hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                       float16 vB[3000]) {
#pragma HLS inline off
  for (int i = 0; i < 3000; i++) {
#pragma HLS pipeline II = 1
    fifo_B_from_off_chip_to_S0.write(vB[i]);
  }
}

void load_vC_for_task0(hls::stream<float16> &fifo_C_from_off_chip_to_S0,
                       float16 vC[3000]) {
#pragma HLS inline off
  for (int i = 0; i < 3000; i++) {
#pragma HLS pipeline II = 1
    fifo_C_from_off_chip_to_S0.write(vC[i]);
  }
}

void load_vA_for_task0(hls::stream<float16> &fifo_A_from_off_chip_to_S0,
                       float16 vA[2600]) {
#pragma HLS inline off
  for (int i = 0; i < 2600; i++) {
#pragma HLS pipeline II = 1
    fifo_A_from_off_chip_to_S0.write(vA[i]);
  }
}

void store_vB_for_task0(hls::stream<float16> &fifo_B_to_off_chip,
                        float16 vB[3000]) {
#pragma HLS inline off
  for (int i = 0; i < 3000; i++) {
#pragma HLS pipeline II = 1
    vB[i] = fifo_B_to_off_chip.read();
  }
}

void FT0_level0(float alpha, hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                hls::stream<float16> &fifo_C_from_off_chip_to_S0,
                hls::stream<float16> &fifo_A_from_off_chip_to_S0,
                hls::stream<float16> &fifo_B_to_off_chip) {
#pragma HLS inline off
  float C_0[200][16];
  // FT0
#pragma HLS array_partition variable = C_0 cyclic factor = 5 dim = 1
#pragma HLS array_partition variable = C_0 cyclic factor = 16 dim = 2
  float C_1[200][16];
  // FT0
#pragma HLS array_partition variable = C_1 cyclic factor = 5 dim = 1
#pragma HLS array_partition variable = C_1 cyclic factor = 16 dim = 2
  float A[200][200];
#pragma HLS array_partition variable = A cyclic factor = 5 dim = 1
#pragma HLS array_partition variable = A cyclic factor = 50 dim = 2
  read_A_FT0(A, fifo_A_from_off_chip_to_S0);
  read_C_FT0(C_0, fifo_C_from_off_chip_to_S0, 0);
  for (int j0 = 0; j0 < 15; j0++) {
    if (j0 % 2 == 0) {
      read_C_FT0(C_1, fifo_C_from_off_chip_to_S0, j0 + 1);
      FT0_level1(alpha, fifo_B_from_off_chip_to_S0, fifo_C_from_off_chip_to_S0,
                 fifo_A_from_off_chip_to_S0, fifo_B_to_off_chip, C_0, A, j0);
    } else if (j0 % 2 == 1) {
      read_C_FT0(C_0, fifo_C_from_off_chip_to_S0, j0 + 1);
      FT0_level1(alpha, fifo_B_from_off_chip_to_S0, fifo_C_from_off_chip_to_S0,
                 fifo_A_from_off_chip_to_S0, fifo_B_to_off_chip, C_1, A, j0);
    }
  }
}
void compute_FT0_level1(float alpha,
                        hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                        hls::stream<float16> &fifo_C_from_off_chip_to_S0,
                        hls::stream<float16> &fifo_A_from_off_chip_to_S0,
                        hls::stream<float16> &fifo_B_to_off_chip,
                        float C[200][16], float A[200][200], int j0, int i0,
                        float B_0[50][16], float B_1[50][16],
                        float B_2[50][16]) {
#pragma HLS inline off
#pragma HLS dataflow
  read_B_FT0(B_0, fifo_B_from_off_chip_to_S0, i0 + 1, j0);
  task0_intra(alpha, C, A, j0, B_1, i0);
  task1_intra(alpha, C, A, j0, B_1, i0);
  write_B_FT0(B_2, fifo_B_to_off_chip, i0 - 1, j0);
}

void FT0_level1(float alpha, hls::stream<float16> &fifo_B_from_off_chip_to_S0,
                hls::stream<float16> &fifo_C_from_off_chip_to_S0,
                hls::stream<float16> &fifo_A_from_off_chip_to_S0,
                hls::stream<float16> &fifo_B_to_off_chip, float C[200][16],
                float A[200][200], int j0) {
#pragma HLS inline off
  float B_0[50][16];
  // FT0
#pragma HLS array_partition variable = B_0 cyclic factor = 50 dim = 1
#pragma HLS array_partition variable = B_0 cyclic factor = 16 dim = 2
  float B_1[50][16];
  // FT0
#pragma HLS array_partition variable = B_1 cyclic factor = 50 dim = 1
#pragma HLS array_partition variable = B_1 cyclic factor = 16 dim = 2
  float B_2[50][16];
  // FT0
#pragma HLS array_partition variable = B_2 cyclic factor = 50 dim = 1
#pragma HLS array_partition variable = B_2 cyclic factor = 16 dim = 2
  read_B_FT0(B_0, fifo_B_from_off_chip_to_S0, 0, j0);
  for (int i0 = 0; i0 < 4; i0++) {
    if (i0 % 3 == 0) {
      //     read_B_FT0(B_1, fifo_B_from_off_chip_to_S0, i0+1, j0);
      //     task0_intra(alpha, C, A, j0, B_0, i0);
      //     task1_intra(alpha, C, A, j0, B_0, i0);
      //     write_B_FT0(B_2, fifo_B_to_off_chip, i0-1, j0);
      compute_FT0_level1(alpha, fifo_B_from_off_chip_to_S0,
                         fifo_C_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0,
                         fifo_B_to_off_chip, C, A, j0, i0, B_1, B_0, B_2);
    } else if (i0 % 3 == 1) {
      //     read_B_FT0(B_2, fifo_B_from_off_chip_to_S0, i0+1, j0);
      //     task0_intra(alpha, C, A, j0, B_1, i0);
      //     task1_intra(alpha, C, A, j0, B_1, i0);
      //     write_B_FT0(B_0, fifo_B_to_off_chip, i0-1, j0);
      compute_FT0_level1(alpha, fifo_B_from_off_chip_to_S0,
                         fifo_C_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0,
                         fifo_B_to_off_chip, C, A, j0, i0, B_2, B_1, B_0);
    } else if (i0 % 3 == 2) {
      //     read_B_FT0(B_0, fifo_B_from_off_chip_to_S0, i0+1, j0);
      //     task0_intra(alpha, C, A, j0, B_2, i0);
      //     task1_intra(alpha, C, A, j0, B_2, i0);
      //     write_B_FT0(B_1, fifo_B_to_off_chip, i0-1, j0);
      compute_FT0_level1(alpha, fifo_B_from_off_chip_to_S0,
                         fifo_C_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0,
                         fifo_B_to_off_chip, C, A, j0, i0, B_0, B_2, B_1);
    }
  }
  write_B_FT0(B_0, fifo_B_to_off_chip, 3, j0);
}
void task0_intra(float alpha, float C[200][16], float A[200][200], int j0,
                 float B[50][16], int i0) {
#pragma HLS inline off
  int j;
  int i;
  int k;
  for (int k0 = 0; k0 < 40; k0++) {
#pragma HLS pipeline II = 2
    for (int j1 = 0; j1 < 16; j1++) {
#pragma HLS unroll
      for (int i1 = 0; i1 < 50; i1++) {
#pragma HLS unroll
        for (int k1 = 0; k1 < 5; k1++) {
#pragma HLS unroll
          j = j0 * 16 + j1;
          i = i0 * 50 + i1;
          k = k0 * 5 + k1;
          B[i1][j1] = B[i1][j1] + A[k][i] * C[k][j1];
        }
      }
    }
  }
}

void task1_intra(float alpha, float C[200][16], float A[200][200], int j0,
                 float B[50][16], int i0) {
#pragma HLS inline off
  int j;
  int i;
  for (int j1 = 0; j1 < 16; j1++) {
#pragma HLS unroll
    for (int i1 = 0; i1 < 50; i1++) {
#pragma HLS unroll
      j = j0 * 16 + j1;
      i = i0 * 50 + i1;
      B[i1][j1] = B[i1][j1] * alpha;
    }
  }
}

void read_A_FT0(float A[200][200],
                hls::stream<float16> &fifo_A_from_off_chip_to_S0) {
#pragma HLS inline off
  for (int d0 = 0; d0 < 200; d0++) {
    for (int d1 = 0; d1 < 208; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_A_from_off_chip_to_S0.read();
      if (d1 + 0 < 200)
        A[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      if (d1 + 1 < 200)
        A[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      if (d1 + 2 < 200)
        A[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      if (d1 + 3 < 200)
        A[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      if (d1 + 4 < 200)
        A[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      if (d1 + 5 < 200)
        A[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      if (d1 + 6 < 200)
        A[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      if (d1 + 7 < 200)
        A[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      if (d1 + 8 < 200)
        A[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      if (d1 + 9 < 200)
        A[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      if (d1 + 10 < 200)
        A[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      if (d1 + 11 < 200)
        A[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      if (d1 + 12 < 200)
        A[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      if (d1 + 13 < 200)
        A[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      if (d1 + 14 < 200)
        A[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      if (d1 + 15 < 200)
        A[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}

void read_C_FT0(float C[200][16],
                hls::stream<float16> &fifo_C_from_off_chip_to_S0, int j0) {
#pragma HLS inline off
  if (j0 >= 15) {
    return;
  }
  for (int d0 = 0; d0 < 200; d0++) {
    for (int d1 = 0; d1 < 16; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_C_from_off_chip_to_S0.read();
      C[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      C[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      C[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      C[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      C[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      C[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      C[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      C[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      C[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      C[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      C[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      C[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      C[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      C[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      C[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      C[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}

void read_B_FT0(float B[50][16],
                hls::stream<float16> &fifo_B_from_off_chip_to_S0, int i0,
                int j0) {
#pragma HLS inline off
  if (j0 >= 15 || i0 >= 4) {
    return;
  }
  for (int d0 = 0; d0 < 50; d0++) {
    for (int d1 = 0; d1 < 16; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo = fifo_B_from_off_chip_to_S0.read();
      B[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
      B[d0 + 0][d1 + 0 + 1] = tmp_fifo[1];
      B[d0 + 0][d1 + 0 + 2] = tmp_fifo[2];
      B[d0 + 0][d1 + 0 + 3] = tmp_fifo[3];
      B[d0 + 0][d1 + 0 + 4] = tmp_fifo[4];
      B[d0 + 0][d1 + 0 + 5] = tmp_fifo[5];
      B[d0 + 0][d1 + 0 + 6] = tmp_fifo[6];
      B[d0 + 0][d1 + 0 + 7] = tmp_fifo[7];
      B[d0 + 0][d1 + 0 + 8] = tmp_fifo[8];
      B[d0 + 0][d1 + 0 + 9] = tmp_fifo[9];
      B[d0 + 0][d1 + 0 + 10] = tmp_fifo[10];
      B[d0 + 0][d1 + 0 + 11] = tmp_fifo[11];
      B[d0 + 0][d1 + 0 + 12] = tmp_fifo[12];
      B[d0 + 0][d1 + 0 + 13] = tmp_fifo[13];
      B[d0 + 0][d1 + 0 + 14] = tmp_fifo[14];
      B[d0 + 0][d1 + 0 + 15] = tmp_fifo[15];
    }
  }
}

void write_B_FT0(float B[50][16], hls::stream<float16> &fifo_B_to_off_chip,
                 int i0, int j0) {
#pragma HLS inline off
  if (i0 < 0 || j0 < 0) {
    return;
  }
  for (int d0 = 0; d0 < 50; d0++) {
    for (int d1 = 0; d1 < 16; d1 += 16) {
#pragma HLS pipeline II = 1
      float16 tmp_fifo;
      tmp_fifo[0] = B[d0 + 0][d1 + 0 + 0];
      tmp_fifo[1] = B[d0 + 0][d1 + 0 + 1];
      tmp_fifo[2] = B[d0 + 0][d1 + 0 + 2];
      tmp_fifo[3] = B[d0 + 0][d1 + 0 + 3];
      tmp_fifo[4] = B[d0 + 0][d1 + 0 + 4];
      tmp_fifo[5] = B[d0 + 0][d1 + 0 + 5];
      tmp_fifo[6] = B[d0 + 0][d1 + 0 + 6];
      tmp_fifo[7] = B[d0 + 0][d1 + 0 + 7];
      tmp_fifo[8] = B[d0 + 0][d1 + 0 + 8];
      tmp_fifo[9] = B[d0 + 0][d1 + 0 + 9];
      tmp_fifo[10] = B[d0 + 0][d1 + 0 + 10];
      tmp_fifo[11] = B[d0 + 0][d1 + 0 + 11];
      tmp_fifo[12] = B[d0 + 0][d1 + 0 + 12];
      tmp_fifo[13] = B[d0 + 0][d1 + 0 + 13];
      tmp_fifo[14] = B[d0 + 0][d1 + 0 + 14];
      tmp_fifo[15] = B[d0 + 0][d1 + 0 + 15];
      fifo_B_to_off_chip.write(tmp_fifo);
    }
  }
}

// extern "C"{
void kernel_nlp(float alpha, float16 vB_for_task0[3000],
                float16 vA_for_task0[2600], float16 vC_for_task0[3000]) {

#pragma HLS INTERFACE m_axi port = alpha offset = slave bundle = kernel_alpha
#pragma HLS INTERFACE m_axi port = vB_for_task0 offset = slave bundle =        \
    kernel_vB_for_task0
#pragma HLS INTERFACE m_axi port = vA_for_task0 offset = slave bundle =        \
    kernel_vA_for_task0
#pragma HLS INTERFACE m_axi port = vC_for_task0 offset = slave bundle =        \
    kernel_vC_for_task0
#pragma HLS INTERFACE s_axilite port = alpha bundle = control
#pragma HLS INTERFACE s_axilite port = vB_for_task0 bundle = control
#pragma HLS INTERFACE s_axilite port = vA_for_task0 bundle = control
#pragma HLS INTERFACE s_axilite port = vC_for_task0 bundle = control
#pragma HLS DATA_PACK VARIABLE = alpha
#pragma HLS DATA_PACK VARIABLE = vB_for_task0
#pragma HLS DATA_PACK VARIABLE = vA_for_task0
#pragma HLS DATA_PACK VARIABLE = vC_for_task0
#pragma HLS INTERFACE s_axilite port = return bundle = control

#pragma HLS dataflow

  hls::stream<float16> fifo_B_from_off_chip_to_S0;
#pragma HLS stream variable = fifo_B_from_off_chip_to_S0 depth = 512
  hls::stream<float16> fifo_C_from_off_chip_to_S0;
#pragma HLS stream variable = fifo_C_from_off_chip_to_S0 depth = 512
  hls::stream<float16> fifo_A_from_off_chip_to_S0;
#pragma HLS stream variable = fifo_A_from_off_chip_to_S0 depth = 512
  hls::stream<float16> fifo_B_to_off_chip;
#pragma HLS stream variable = fifo_B_to_off_chip depth = 512

  load_vB_for_task0(fifo_B_from_off_chip_to_S0, vB_for_task0);
  load_vC_for_task0(fifo_C_from_off_chip_to_S0, vC_for_task0);
  load_vA_for_task0(fifo_A_from_off_chip_to_S0, vA_for_task0);

  FT0_level0(alpha, fifo_B_from_off_chip_to_S0, fifo_C_from_off_chip_to_S0,
             fifo_A_from_off_chip_to_S0, fifo_B_to_off_chip);

  store_vB_for_task0(fifo_B_to_off_chip, vB_for_task0);
}
//}
